### ISSUE TITLE
Community: There is no active state for the left navigation

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#170]
Just as a reminder so we fix this:

**Community section** (no active state)
![image](https://user-images.githubusercontent.com/3634580/36997042-acad1c62-20b8-11e8-9d87-b26e3170d4d7.png)

**Documentation** (has active state)
![image](https://user-images.githubusercontent.com/3634580/36997055-babbee0a-20b8-11e8-97ae-9e49bfc5ac77.png)

**Comment by abjerner** [comment]
Fixed by https://github.com/umbraco/OurUmbraco/pull/180

**Comment by nul800sebastiaan** [comment]
👍
