### ISSUE TITLE
Community: Breadcrumb should include "Community"

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#172]
**Meetups** is at the third level in the site structure, so the breadcrumb should also include **Community** (which is at level 2).

All the new community pages seems to be affected, so it probably only a single place that we have to fix.

@nul800sebastiaan If possible, feel free to assign this to me ;)

![image](https://user-images.githubusercontent.com/3634580/36997610-7a44a2e8-20ba-11e8-8825-8a567e665cb9.png)

**Comment by nul800sebastiaan** [comment]
It will do as soon as the community page is no longer hidden (naviHide is currently 0) :-)

**Comment by abjerner** [comment]
Ah, I see. But should a breadcrumb really listen for `umbracoNaviHide`? I think this is specifically one of those moments where `umbracoNaviHide` should be ignored.

But as long as it works when the pages are made public ;)
