### ISSUE TITLE
Top karma earners last week

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#174]
Both titles are **Top karma earners last week**, but the stats are different. The top one should show the current week - as it used to do.

![image](https://user-images.githubusercontent.com/3634580/37003939-0ef37ec8-20cf-11e8-973b-67f4f5a04d83.png)

**Comment by nul800sebastiaan** [comment]
For some reason this list was based on last year's results, not this years haha
https://github.com/umbraco/OurUmbraco/commit/6d4531a4c9bde5b1b67a4b4d965b29ca2fc9e2c7

**Comment by nul800sebastiaan** [comment]
Hmm, now it's just not showing last week and this week.. oops :)

**Comment by abjerner** [comment]
Whichever week I have the most karma is fine ;)

**Comment by nul800sebastiaan** [comment]
Happy? ;-)

![image](https://user-images.githubusercontent.com/304656/37028029-67d13080-2133-11e8-8c26-68a1b60cbf12.png)

**Comment by abjerner** [comment]
![sy3s6](https://user-images.githubusercontent.com/3634580/37028144-bd48ac1e-2133-11e8-8a8a-c3854cc18262.gif)
