### ISSUE TITLE
Adjust tags in sidebar menu

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#202]
I think styles of tags in the sidebar menu should be adjusted a bit.

![image](https://user-images.githubusercontent.com/2919859/37964733-ca915e8a-31c2-11e8-9768-442a95bfeb43.png)

E.g. similar to how it looks in forum overview page.
![image](https://user-images.githubusercontent.com/2919859/37964761-e37e1500-31c2-11e8-97a3-dc295e2cde61.png)

Something like this:

```
.quick-menu {
     .forum-thread {
          flex-wrap: wrap;

          .forum-thread-text {
                 flex: 1 0 100%;
          }
          .category {
                 .cat {
                    margin-top: 10px;
                     max-width: 100%;
                 }
          }
     }
}

```

![image](https://user-images.githubusercontent.com/2919859/37964983-bfb38c80-31c3-11e8-82f4-6392ba75ac2c.png)

**Comment by warrenbuckley** [comment]
Looks good to me @bjarnef 
Mind sending us your magic CSS as a PR please :)

**Comment by bjarnef** [comment]
Maybe later, just creating an issue to remember this should be fixed 😁

**Comment by warrenbuckley** [comment]
Thanks again @bjarnef
