### ISSUE TITLE
Console errors on karma leaderboard

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#204]
There are some console errors on this page:
https://our.umbraco.org/community/karma-leaderboard/

![image](https://user-images.githubusercontent.com/2919859/37965313-f4a7b42e-31c4-11e8-8b07-d03591b2afd5.png)

I guess it is because of this image has a space in the url:
http://our.umbraco.org/media/upload/0bd1f83a-f0d4-4f67-84b4-6676de8138f7/BW Profiler.jpg?width=112&height=112&mode=crop&upscale=true

`srcset` attribute apparently don't like spaces inside the url. I think `.Replace(" ", "%20")` will solve this or url encoding the value.

**Comment by nul800sebastiaan** [comment]
Hmmm, I would've thought that was in place already. Might be a different code path though.

https://github.com/umbraco/OurUmbraco/blob/cdc8afdfbd5ef3989dfd68f805a22037a678e9fe/OurUmbraco/Our/Utils.cs#L332

**Comment by bjarnef** [comment]
I get the spaces here :)

![image](https://user-images.githubusercontent.com/2919859/37966131-cb0264cc-31c7-11e8-93fe-8396b5ad25ed.png)

**Comment by bjarnef** [comment]
@nul800sebastiaan how about this helper function?
https://github.com/umbraco/OurUmbraco/blob/06cc377d0cdbca2c643beaeba1e4319eda5356b4/OurUmbraco.Site/Views/Partials/Community/KarmaStatistics.cshtml#L190-L214

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/commit/d6921c30466b5a5e9e4a11227de2dc55d8477828

**Comment by bjarnef** [comment]
@nul800sebastiaan any reason it doesn't reuse this utils method?
https://github.com/umbraco/OurUmbraco/blob/cdc8afdfbd5ef3989dfd68f805a22037a678e9fe/OurUmbraco/Our/Utils.cs#L231-L242
