### ISSUE TITLE
Fix badge classes

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#209]
I noticed on @warrenbuckley 's member profile that the badges didn't have same styling as other places on Our.
https://our.umbraco.org/member/1175

![image](https://user-images.githubusercontent.com/2919859/37976255-5b59eb9e-31e1-11e8-8cfc-4f3df28c52f7.png)

The badges has class names `badge.CssClass`  instead of class names like `mvp`, `c-trib` etc.

![image](https://user-images.githubusercontent.com/2919859/37976355-9c5e8370-31e1-11e8-8dee-3b66b7fdcce4.png)

Furthermore should the casing be consistent with badges in other places on Our e.g. in quick menu: `Admin`,`HQ`, `C-Trib`, etc.

**Comment by warrenbuckley** [comment]
Hmm I can't reproduce this @bjarnef 
This still an issue for you?

**Comment by nul800sebastiaan** [comment]
Oops, it's missing an @ sign. They're all consistent now as well :-)

👍
