### ISSUE TITLE
Add line breaks on Gitter username

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#210]
In mobile layout I think we should add line breaks on Gitter username, twitter and maybe after date too.

![image](https://user-images.githubusercontent.com/2919859/37976873-bf60bb6c-31e2-11e8-90d2-e7e77685cdda.png)

Something like this:

```
.gitter-message {
    .user {
        margin-bottom: 5px;
        display: flex;
        flex-wrap: wrap;
        align-items: baseline;

        .name, .username {
            flex: 1 0 100%;
        }

        .date {
            margin-top: 5px;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/2919859/37977579-4932f868-31e4-11e8-9fed-cfd492222ac4.png)

**Comment by ed-parry** [comment]
@bjarnef Your suggestion works nicely, Bjarne - a lot clearer to read!
