### ISSUE TITLE
Fix & character in recent tweets

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#211]
When tweets contains e.g. the character `&` it doesn't seem to be decoded.
https://twitter.com/warrenbuckley/status/978643318748958727

![image](https://user-images.githubusercontent.com/2919859/37978053-60e638ac-31e5-11e8-8c02-3b5110154c37.png)

**Comment by nul800sebastiaan** [comment]
Need to make sure it's safe and we're not allowing some kind of nasty injections if we `Html.Raw` it.

**Comment by abjerner** [comment]
It seems that the text is already encoded, so we should be able to decode it without any problems. But yes, we must make sure to test whether that is in fact the case. Even though is doesn't use my package (😡), I can try having a look at it ;)

**Comment by nul800sebastiaan** [comment]
😂 Sorry for that ;-)

**Comment by nul800sebastiaan** [comment]
This has been open for a while now and it's still a good idea but it seems like nobody has had time to pick it up.

I'll close this for now and add the `idea` tag so we can find it later when we have some more time to spend on this.

Thanks!
