### ISSUE TITLE
Adjust avatars under map

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#212]
When zooming in on the map on this page, the might be a bit too much distance between the avatars:
https://our.umbraco.org/community/

![image](https://user-images.githubusercontent.com/2919859/37980000-46a40af0-31ea-11e8-9f0b-012d33ae8e55.png)

I would add this to each item `flex: 0 1 auto;` and then add `justify-content: flex-start;` or `justify-content: center;` on the parent element.

Also add a bit margin to the "Umbraco Community Chat" section.

![image](https://user-images.githubusercontent.com/2919859/37979861-f8fed2f8-31e9-11e8-8691-367fef8153d5.png)

**Comment by warrenbuckley** [comment]
Thanks @bjarnef as I suck at writing CSS :)
