### ISSUE TITLE
Cluster graphic doesn't disappear when zooming

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#213]
When I zoom in on the map or clicking the cluster graphic, it doesn't seem to disappear.

![image](https://user-images.githubusercontent.com/2919859/37980506-94a41afa-31eb-11e8-9b74-20eebc94da3f.png)

e.g. when zooming to max level I still see a cluster graphic with value "5" for Herning, Jutland, Denmark :)

![image](https://user-images.githubusercontent.com/2919859/37980660-e88ecc28-31eb-11e8-9748-d95800af7543.png)

Furthermore at different zoom levels it seems the graphic sometimes are on top on each other instead of having a single cluster graphic, when many markers are close to each other.

![image](https://user-images.githubusercontent.com/2919859/37980758-2907cebc-31ec-11e8-95b6-ccc9247e2b76.png)

![image](https://user-images.githubusercontent.com/2919859/37980799-4f445212-31ec-11e8-82e8-918c644cae23.png)

**Comment by warrenbuckley** [comment]
That's because we have some members with the exact same location or used a generic location. See London for example. Not sure I can do much to combat this @bjarnef 

We hope over time people either update/amend their location so there are less of these

**Comment by bjarnef** [comment]
Okay @warrenbuckley  :) 

However I wonder why these 5 people on the same location then suddenly disappear, when I zoom to much on the position?

![image](https://user-images.githubusercontent.com/2919859/37993653-927180be-320f-11e8-98bf-f45594fc3f9c.png)

![image](https://user-images.githubusercontent.com/2919859/37993691-b94ffe68-320f-11e8-8fe1-a471aaf671ca.png)

![image](https://user-images.githubusercontent.com/2919859/37993739-d8b48648-320f-11e8-8893-e8b4178228a2.png)

**Comment by warrenbuckley** [comment]
OK this is a duplicate issue @bjarnef 

See this one here...
https://github.com/umbraco/OurUmbraco/issues/207
