### ISSUE TITLE
Limit size of emojis in Gitter

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#217]
Should we set a size limit on Gitter emojis? E.g. 20 x 20 px?

![image](https://user-images.githubusercontent.com/2919859/38026150-49cb7d3e-328b-11e8-927e-f22fde8fb111.png)

Updated size:

![image](https://user-images.githubusercontent.com/2919859/38026173-64a5666a-328b-11e8-86da-a6d2e5e407df.png)

Maybe also consider adding `vertical-align: middle`.

```
img.emojione {
    width: 20px;
    height: 20px;
    vertical-align: middle;
}
```

**Comment by warrenbuckley** [comment]
Thanks @bjarnef all pushed
