### ISSUE TITLE
Description missing for Core badge

### ISSUE THREAD

**Issue by greystate** [umbraco/OurUmbraco#223]
Just noticed on [Hendy Racher](https://our.umbraco.org/member/1713)'s profile there is a **Core** badge (others have it as well) which, when clicked, takes you to [the descriptions](https://our.umbraco.org/community/badges/#core) of the other badges, missing a description for the Core badge.

Any other badges being rendered that are missing descriptions?

**Comment by nul800sebastiaan** [comment]
Hmm, the Core badge doesn't mean anything any more. It used to be that you as a non-HQ person had commit rights to the Core, but that's just HQ members now. 

I've unassigned it from people who have it (sorry Hendy and others!).
