### ISSUE TITLE
Introduce new Codegarden badge

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#225]
Assuming that Umbraco already has sufficient data from previous Codegarden ticket purchases, it could be fun to introduce a new Codegarden badge - eg as illustrated below:

![image](https://user-images.githubusercontent.com/3634580/38439031-86a5e5ca-39dc-11e8-83c5-7dd708d06808.png)

The color for the badge is **#FF8B8A** which I've picked from the Codegarden 2018 website. Also, as I have been to a total of five Codegardens so far, the badge shows **X5** similar to how multiple MVP badges are grouped.

**Comment by nul800sebastiaan** [comment]
I would love it but there's a few problems: 

1. Our data is not very good, and it depends on who bought the ticket and if a seat was ever assigned. At best it will be messy and inaccurate for most people.
2. Our privacy policy doesn't allow for sharing data from the Umbraco.com shop with Our Umbraco.

The good news about number 2 is that we're not like Facebook ;-)

Maybe we can one day develop this feature where we ask: "hey. do you want to update your profile with the data from your shop profile?"
But that will require writing an API at the shop first and that's not going to happen any time soon I'm afraid.

I'll close this for now, we might re-open it if we find a good way of doing this.
