### ISSUE TITLE
DoubleClick Ad Scripts Appearing

### ISSUE THREAD

**Issue by kgiszewski** [umbraco/OurUmbraco#229]
Not suggesting anything malevolent but DoubleClick is collecting info on the Our Umbraco site and it's not listed in the privacy policy.

https://our.umbraco.org/privacy-policy/

It only appears every so often and not on every load. I'm using Ghostery (Chrome Extension) to detect these on sites I visit. You'll have to reload a few times to catch it.

I tried to track it down, there are two google scripts that reference DoubleClick.

https://www.googletagmanager.com/gtm.js?id=GTM-NQ556HD

https://www.google-analytics.com/analytics.js

My first reaction was some included script is including this, so it's possible that it is the case still.

![image](https://user-images.githubusercontent.com/4653907/38779101-ad7b9404-4091-11e8-8a93-e6ac5574fadc.png)

Maybe it's intended behavior, just didn't expect ad tracking on Our.

Please close if this is intended.

**Comment by nul800sebastiaan** [comment]
Thanks @kgiszewski 👍 
After some investigation it turns out this was a misconfiguration in google analytics. This has been corrected yesterday and it looks like the new settings have taken effect today.
