### ISSUE TITLE
Cookie popup seems to affect layout

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#230]
I noticed a cookie popup has been added and it seems to afffect the styles/layout.

E.g. for https://our.umbraco.org/download/ in mobile layout.

![image](https://user-images.githubusercontent.com/2919859/38801708-e1388fa2-416a-11e8-8d2f-26514856cb48.png)

compared to opening the menu from other pages.

![image](https://user-images.githubusercontent.com/2919859/38801752-02f693f0-416b-11e8-933f-3f23c4c64347.png)

Furthermore on e.g. project page or the individual project page, there is a lot of margin/padding.

![image](https://user-images.githubusercontent.com/2919859/38801816-2652e808-416b-11e8-8452-973a3f5ed635.png)

![image](https://user-images.githubusercontent.com/2919859/38801838-32cad582-416b-11e8-924e-4c1421557f6b.png)

![image](https://user-images.githubusercontent.com/2919859/38801875-4c3e9bde-416b-11e8-9a82-6d559c13c228.png)

If I remove `height:100%` here it is getting better.

![image](https://user-images.githubusercontent.com/2919859/38801998-96f5e7cc-416b-11e8-95fb-33d1da118466.png)

Also here is has `height:100%`
![image](https://user-images.githubusercontent.com/2919859/38802086-d5216094-416b-11e8-9eff-ceab7ff30b3d.png)

**Comment by nul800sebastiaan** [comment]
It does say that you need to accept cookies for the best experience ;-)

I don't think it's really a problem, choose one of the links and the cookie notice disappears and won't be injected again, everything will be back to normal (no matter which one you choose).

**Comment by bjarnef** [comment]
@nul800sebastiaan 

No, if I reject cookies and refresh the page, I still see all the additional spacing, because of the `height: 100%` on several elements.

![image](https://user-images.githubusercontent.com/2919859/38826591-93c4ef5e-41b0-11e8-94b7-7a18f0f8c6a7.png)

I don't understand why it need cookies for this? It is just css.

![image](https://user-images.githubusercontent.com/2919859/38826712-f3c45840-41b0-11e8-9fe6-5c17e1c06ec9.png)

![image](https://user-images.githubusercontent.com/2919859/38826756-03d27dac-41b1-11e8-9f7b-4235fe19eec5.png)

It seems to be using this plugin https://cookieconsent.insites.com/

It should be possible to either disable to plugin styles (and add what is necessary) or build a custom stylesheet. https://cookieconsent.insites.com/download/ 

But I can't see anywhere is it css https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css it add this styles to the `.box` class.

**Comment by nul800sebastiaan** [comment]
Turns out it had nothing to do with the styling, just me being an idiot 😂 

Spot the problem.. ;-)


![image](https://user-images.githubusercontent.com/304656/38867329-043081d4-4244-11e8-93d0-a0d413d66744.png)

**Comment by bjarnef** [comment]
Much better! 😁🦄

It is not very clear that there is a collapsed "cookie policy" in this corner.

Maybe it should be less hidden?

![image](https://user-images.githubusercontent.com/2919859/38870463-3269ffee-424e-11e8-9a18-fb559924eacc.png)

![image](https://user-images.githubusercontent.com/2919859/38870245-8b314994-424d-11e8-8148-520a77428f64.png)
