### ISSUE TITLE
Karma not always awarded when topic is marked as solution

### ISSUE THREAD

**Issue by dawoe** [umbraco/OurUmbraco#231]
I noticed a couple of time when answer is marked as solution the correct karma amount is not always awarded. Normally you should get 20 points when your answered is marked as solution and it should show the number 100.

Example post with no karma : https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/91596-umbracomodelsbuilderapi-cannot-find-namespace#comment-289284

[Screenshot](https://www.dropbox.com/s/rkx3vznvxb27xap/karma%20error.png?dl=0)

Also these ones have the same issue : 
https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/91571-move-page-to-trash-using-sql
https://our.umbraco.org/projects/developer-tools/usync/usync/91594-ysod-with-umbraco-7102

Don't know what is causing this. Because it works correctly most of the times. For example this one : 
https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/91518-error-rendermvcindex

**Comment by Mivaweb** [comment]
Same here, first noticed it this morning.

/Michaël

**Comment by nul800sebastiaan** [comment]
Just to confirm: I've seen the problem, I'll have a look at it soon and whatever happened it can be corrected. :-)

**Comment by dawoe** [comment]
This seems to be working again

**Comment by nul800sebastiaan** [comment]
I'm keeping my 🤞 that this just happened to fix itself magically somehow. I'll close this issue for now until we can reproduce it.

Thanks!
