### ISSUE TITLE
Add 'was this page helpful' option to docs

### ISSUE THREAD

**Issue by tcmorris** [umbraco/OurUmbraco#246]
When viewing documentation, it's possible that you do or don't find what you are looking for. As discussed at Codegarden, it would be great if there was an option to provide some feedback as to whether or not the documentation was helpful, and if not, then why not? 

Potential implementation:

Place at the bottom of the page with two options.
- Yes, when clicked - great, feel free to suggest any updates.
- Not really, when clicked - ah ok, let us know what we could do to improve.

Or something like that. The options could link through to the issue tracker on Github or some other method of providing feedback.

**Comment by skttl** [comment]
I was just looking for some help on using the ncNodeName filter for naming templates on Nested Content, and found this very helpful article: https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content#configuring-nested-content

Really good stuff - so I thought it would be great if you could give some kind of quick feedback (like the h5's in the forum) saying you found this article helpful.

This feedback could then be used to see if any articles could be made better, or be used as an example when writing new articles.

**Comment by tcmorris** [comment]
New docs site with this feature: https://docs.umbraco.com/
