### ISSUE TITLE
Feature suggestion: Add "Strikethrough" option to the markdown editor

### ISSUE THREAD

**Issue by BatJan** [umbraco/OurUmbraco#253]
I'm missing the "Striketrhough" option when editing a post. If for instance you realise what you have written is wrong or not clear enough it would be nice to make a strikethrough of the text no longer relevant, so it's very clear.

**Comment by jamiepollock** [comment]
@BatJan I've done some investigation into this and sadly it's currently not possible.

The logic for markdown comes in the form of a version of Pagedown and the `Markdown.Converter.js`. Sadly this is [linked out to a CDN](https://github.com/umbraco/OurUmbraco/blob/fe254ea99fda756278bffee96947a821910a6f30/OurUmbraco.Site/Views/Master.cshtml#L26) in `Master.cshtml` so we can not modify the code even though [there are files in the repo that parallel it](https://github.com/umbraco/OurUmbraco/search?l=JavaScript&q=Markdown.Editor.js).

It might be possible to increase the version of Pagedown we link out to but this might have an impact on the current editor.

**Comment by jamiepollock** [comment]
@BatJan yea, I completely agree! I was disappointed to see strikethrough wasn't supported by Pagedown. The project has numerous issues and don't seem overly well maintained in the last 6 months which is disappointing.

The semi-good news is [the editor](https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/Assets/js/editor.min.js#L2-L3) included [here](https://github.com/umbraco/OurUmbraco/blob/fe254ea99fda756278bffee96947a821910a6f30/OurUmbraco.Site/Views/Master.cshtml#L38) could potentially be switched out for another.

I'm not saying it'll be super easy but there is potential here. I'll have a look into [Stackedit](https://github.com/benweet/stackedit). Although that has hundreds of issues against it.

Thanks for the suggestions!

**Comment by nul800sebastiaan** [comment]
Hey guys, thanks for creating this issue, I set it to `up-for-grabs` but then realized it wasn't actually possible at the moment without a huge overhaul. I will close this for now and add the `idea` label on it so we can revisit it in the future when we/you have a more time to work on this.
