### ISSUE TITLE
Feature suggestion: Option to edit post immediately after it has been created

### ISSUE THREAD

**Issue by BatJan** [umbraco/OurUmbraco#260]
I noticed that whenever one creates a new post the context menu is limited to only have 2 of the usual options. One is delete and the other one I think is "Copy link".

However I find that I make many typos when I write so after posting I need to edit the post. But currently one will need to refresh the page using ctrl+f5 in order to see the full range of options on the post where it's then possible to edit instead of being able to do it immediately.

Does this make sense? :-) Don't know if it's at all possible though. But would be nice though.

I'll be happy to have a look at it myself when I get some spare time and figure out.

**Comment by greystate** [comment]
Yep - I’ve actually seen many complain about not being able to edit their post (because they hadn’t refreshed).

**Comment by nul800sebastiaan** [comment]
Oops, wrong button! 🙈 

I remember we had the same problem when editing a comment, so I added a refresh at some point after submitting the edit. It's not very sexy but that would be the only easy way to make this work, only after the refresh do we have the id of the post available to be able to show the appropriate buttons. 

Of course the ideal solution would be to send the correct data back after posting and populate the buttons that way.

**Comment by jamiepollock** [comment]
@BatJan @nul800sebastiaan hey guys, I have a fix in place for this. :)

**Comment by nul800sebastiaan** [comment]
Resolved with #266
