### ISSUE TITLE
The Video count does not seem to be working ( or at least needs updating! )

### ISSUE THREAD

**Issue by readingdancer** [umbraco/OurUmbraco#264]
I have just looked at the video page to view the #CG18 videos, currently they all say they have been viewed zero times... but if you click through to one of the videos, you will find that they have actually been viewed.

https://our.umbraco.org/videos/

At the time of writing this, the following video has been viewed 96 times:

https://vimeo.com/273473715

What I would expect to see is the counter showing a number at least similar to the real count on Vimeo, perhaps with a sub note to say the counter is updated every X hours or days.

**Comment by abjerner** [comment]
@ed-parry I just had a look at what goes wrong, and it is because the play count isn't returned properly by the Vimeo API (there is a `plays` property, but the value is `null`).

I think the play count was there back in February when we launched the new community section. I will look into why the play count isn't returned ;)

**Comment by abjerner** [comment]
Apparently the play count isn't available if the access token only has the `public` scope, but it is when using an access token with the `private` scope. Which may actually be a bug on Vimeo's end (or silly behavior at best) as my own access token with the `private` scope can access the play count of Umbraco's videos.

@nul800sebastiaan would it be possible to switch to an access token with the `private` scope? If you go to https://developer.vimeo.com/apps/ and select the app used for the Our Umbraco site, you can generate a new access token (the feature lives under the *Authentication* tab, and then at the very bottom of the page).

@ed-parry it might still be a good idea to check whether a given video has any plays, as new videos might not for some time. If you're looking to do another PR, you can find the code for it here (there is already a similar check for likes):
https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/Views/Partials/Videos/Home.cshtml#L150

**Comment by ed-parry** [comment]
Makes sense, thanks @abjerner. I guess they're hiding some of the details unless the scope is private, but if it doesn't have to be associated to the upload account doesn't make much sense to me, but can't say I understand the Vimeo API.

Thanks for the pointer too - I may take a look, and could be worthwhile updating the timestamp at the same time - the latest video on the page is only 28 seconds long and so just lists as "0 min" which looks a little strange :)

**Comment by nul800sebastiaan** [comment]
I've now switched to a token that uses the `private` scope as well. Is that all I need to do and then refresh the cache or was there more required?

**Comment by abjerner** [comment]
@nul800sebastiaan should be enough to update the cache ... or just wait a bit as the cache should be automatically updated ;)

**Comment by readingdancer** [comment]
great news, well done everyone for diagnosing and fixing this one 👍

**Comment by nul800sebastiaan** [comment]
That's more like it, the play count is now indeed updating correctly! 👍
