### ISSUE TITLE
Add a link to forgotten password page to let you login again

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/OurUmbraco#267]
![image](https://user-images.githubusercontent.com/1674590/41845631-0954ab78-786c-11e8-9ecd-a8a3d402e9c0.png)

The thank you page after the forgotten password page shows a nice message to say "You can now login" but there is no link to the login page.

Ideally that text should have a link to:

https://our.umbraco.com/member/login

Nice and easy.

**Comment by PeteDuncanson** [comment]
See: https://github.com/umbraco/OurUmbraco/blob/4fac7f0b9156b6f832628487231d6b11453158ae/OurUmbraco.Site/umbraco/Views/common/dialogs/login.html#L225

Mildly complicated as we will need to localise it but doable.

**Comment by ed-parry** [comment]
I think it could be this page for the fix @PeteDuncanson:
https://github.com/umbraco/OurUmbraco/blob/4fac7f0b9156b6f832628487231d6b11453158ae/OurUmbraco.Site/Views/Partials/Members/ResetPassword.cshtml

Your link is within the Umbraco source which could still benefit from a helpful link, but I don't think it's the page we get referred to from Our. The localisation part made me wonder! :)

**Comment by PeteDuncanson** [comment]
@ed	ooh good spot, habit of searching the Umbraco CMS code :)

The line I mention originally is here too: https://github.com/umbraco/OurUmbraco/blob/4fac7f0b9156b6f832628487231d6b11453158ae/OurUmbraco.Site/Views/Partials/Members/ForgotPassword.cshtml#L38

So we have two places to fix...which seems odd?

**Comment by ed-parry** [comment]
It's just the `ResetPassword.cshtml` isn't it? The `ForgotPassword.cshtml` is effectively the end of that flow, with `ResetPassword.cshtml` bringing them back to the site from the email?

**Comment by nul800sebastiaan** [comment]
☝️ What Ed said! 😁
