### ISSUE TITLE
Page title truncated

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#269]
I just saw this forum thread on our https://our.umbraco.com/forum/using-umbraco-and-getting-started/92607-ould-i-be-better-off-dropping-umbraco-and-building-my-site-using-aspnet-mvc-hosted-on-azure

and I am wondering why this page title and url is truncated to "_ould i be better off dropping umbraco and building my site using aspnet mvc hosted on azure_" without "_W_"? 🤔 

![image](https://user-images.githubusercontent.com/2919859/41971855-24de06aa-7a10-11e8-9322-60d9a0acec4a.png)

**Comment by nul800sebastiaan** [comment]
Dunno. :-) 

It's not a systemic problem at the moment, might be related to renaming it, I'm not worried about it. :)
