### ISSUE TITLE
Update name reply-name

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#283]
I know @leekelleher is famous, MVP and awesome contributer to Umbraco, but can't I just reply **Lee Kelleher** instead of **Lee KelleherMVP 8xadminc-trib**? 😁🦄 

![image](https://user-images.githubusercontent.com/2919859/43130574-44164078-8f37-11e8-9ea1-f5986310b623.png)

**Comment by nul800sebastiaan** [comment]
lol!

I thought this was fixed.. weird.

**Comment by hemraker** [comment]
I do think that is the only proper way to address that fine gentleman.

**Comment by leekelleher** [comment]
I'm printing new business cards as we speak! 😆
