### ISSUE TITLE
Idea: Add "workaround" option on a post?

### ISSUE THREAD

**Issue by BatJan** [umbraco/OurUmbraco#286]
I just read this post https://our.umbraco.com/forum/umbraco-forms/92096-how-to-un-approve-record#comment-294310 where Ismail describes a workaround to an issue, which currently does not have a proper solution and it got me wondering if it would make sense to have an option to mark a post as a viable workaround if no proper/real solution exists to a certain issue?

Thoughts on this? 🤔

**Comment by nul800sebastiaan** [comment]
Sorry for the (very) late reply @BatJan  🙈

It's a nice thought mate but I don't think we want to complicate the forum with something like that. 😄
