### ISSUE TITLE
Contribute link is broken

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#293]
It seems the contribute link in the navigation on Our is broken.

At the moment it links to:
https://our.umbraco.com/contribute/ which redirect to https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/docs/CONTRIBUTING.md which doesn't exists anymore.

I guess it should link to this instead.
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING.md

Maybe there are other broken links when these files have been moved to this `.github` folder?

**Comment by nul800sebastiaan** [comment]
Unfortunately not much we can do, the redirect has been updated but since it used to be a 301, your browser caches it. A cache refresh helps. 😕
