### ISSUE TITLE
Link to public profile page is broken

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#294]
When I click the "view my public profile" link in the quick menu it now seems to return an error page.
E.g. the link to my profile page https://our.umbraco.com/member/12901

![screenshot_20180903-143655_chrome](https://user-images.githubusercontent.com/2919859/44987747-8a916e80-af88-11e8-9a75-206790320bd8.jpg)

https://our.umbraco.com/error/?aspxerrorpath=/member/

**Comment by nul800sebastiaan** [comment]
Ah shoot, I might have deployed something a little prematurely, thanks @bjarnef - I'll have a look very soon! 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/commit/0ee0de0c075164a7436a920bf718f750b5da4a95
