### ISSUE TITLE
Adjust form fields on edit profile

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#295]
The form fields when eiditing profile need a bit adjustments for mobile devices. It would probably be better to place the labels above the form fields on mobile screen sizes.

![screenshot_20180903-144305_chrome](https://user-images.githubusercontent.com/2919859/44987689-57e77600-af88-11e8-99ca-b447e6df9d3b.jpg)

**Comment by villian** [comment]
added pull request - https://github.com/umbraco/OurUmbraco/pull/296
