### ISSUE TITLE
Heading is the same for updated and popular packages

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#298]
It seems the heading _Browse most popular packages_ it the same for these pages:
https://our.umbraco.com/packages/?orderBy=updateDate
https://our.umbraco.com/packages/?orderBy=popularity

However for the other filter options the heading change:
https://our.umbraco.com/packages/?version=7
https://our.umbraco.com/packages/?version=6
https://our.umbraco.com/packages/?version=4

https://our.umbraco.com/packages/?category=Collaboration
https://our.umbraco.com/packages/?category=Backoffice%20extensions

etc.

It would also be nice to highlight the active nav item, like on this page https://our.umbraco.com/documentation/Extending/Section-Trees/

**Comment by villian** [comment]
added PR - https://github.com/umbraco/OurUmbraco/pull/300
