### ISSUE TITLE
Page for all releases is a bit hidden 

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#315]
I think the page for all releases (incl. latest, previous and upcoming) is a bit hidden after the download page  was re-designed. https://our.umbraco.com/download/

If you don't know Our very well, it might bit hard to find.

![image](https://user-images.githubusercontent.com/2919859/46602583-e6ec2e80-caf0-11e8-95d4-15c2a96d9c00.png)

And since the download page doesn't list the subpages as here:
![image](https://user-images.githubusercontent.com/2919859/46602620-f8cdd180-caf0-11e8-8cd8-102fda2d79d8.png)

Maybe it should show the left navigation with the subpages as all the other toplevel navigation items does (except forum): https://our.umbraco.com/forum/

It could maybe list the current version "Download 7.12.3" (as a button since it actually does something - download a .zip file and not just a link). Next to this button or below it a link to the previous releases.

Maybe it could also show progress of upcoming patch, minor and major version?

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - would agree that it's a bit hard to find. I think all your proposals sound pretty good!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
