### ISSUE TITLE
Crop size of image used as package icon

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#320]
I think we should crop the size of the image, which are use as package icon, which appear in the results of packages.

E.g. try searching for "h-tag":

![image](https://user-images.githubusercontent.com/2919859/46856926-01cbe500-ce08-11e8-90f0-19dfe15c86ab.png)

E.g. this default image (icon) for this package, breaks the layout a bit.
https://our.umbraco.com/packages/backoffice-extensions/tag-manager/

**Comment by nul800sebastiaan** [comment]
Hehe, yeah that looks less than ideal! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Matthew-Wise** [comment]
This can be closed as the PR is merged and live :)
