### ISSUE TITLE
The Compare Versions page links to the OLD issue tracker.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/OurUmbraco#345]
If you compare two versions of Umbraco on the Our website like this page:

https://our.umbraco.com/download/releases/compare?from=7.12.3&to=7.12.4

The links point back to the old issue tracker and for all new issues since the change over to GitHub, these links should be pointing to GitHub issues.

**Comment by nul800sebastiaan** [comment]
Thanks @readingdancer - that's an oversight! Should be easy to fix, we have a switch in the release notes already that lists the correct links. Want to give it a go?

**Comment by readingdancer** [comment]
Hi @nul800sebastiaan 

I would be happy to do this if I could get the Our solution up and running again, but I am still sat in the limo with a broken DB, if you recall, the DB in the solution is out of sync with your live DB. It would be great if someone could fix this so its easy to spin up the OUR solution again :)

Cheers,

Chris

**Comment by nul800sebastiaan** [comment]
Yep, I remember that. I've sat next to two people at the hackathon last week who did a fresh clone of the repository and the database was just fine. We did need to increase a SQL server timeout for one of them and that change has now been committed as well. So I would encourage you to try again with a fresh clone.

The data is still outdated but that is just fine, you should have all the data needed to get the project running. If there's anything explicitly missing that is really needed then let me know and I can help you create it.

**Comment by readingdancer** [comment]
Hi @nul800sebastiaan 
I'll try and give it another go later and will let you know, fingers crossed :)
Cheers, Chris

**Comment by readingdancer** [comment]
@nul800sebastiaan - Happy New Year :)

It took me a couple of months to get back to this, but finally I've submitted a Pull request to fix this issue. It took me a fair amount of time to get the solution actually working as the ZIP'ed DB is in a pretty unusable state!

For example, because all the users have been deleted, the back office is almost completely crippled as every page you try and edit errors with a AutoMapper error related to the users. The fix for this was to run the following two SQL statements:

update umbraconode set nodeUser = 0
update cmsDocument set documentUser = 0

I just thought it would be worth mentioning in case you can add this to your export process, also the actual pages are quite out of date as the structure of the live site is now different. This release page doesn't actually exist in the test DB, so I had to re-add it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/372
