### ISSUE TITLE
Package Details Page: Show the creator's badges under their profile picture

### ISSUE THREAD

**Issue by prjseal** [umbraco/OurUmbraco#354]
I think it would be good to be able to see the badges of the person who created the package under their profile picture.

It would give the person looking at the package more confidence if they can see the creator has badges such as HQ, MVP, C-Trib, Admin etc.

It would look something like this:

![Diplo Trace Log Viewer](https://i.imgur.com/0mdTHAD.jpg)

**Comment by nul800sebastiaan** [comment]
Sounds good to me @prjseal ! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by prjseal** [comment]
Thanks @nul800sebastiaan 
I'll try and have a go at it. Will be my first PR on Our, if someone else doesn't beat me to it.

**Comment by prjseal** [comment]
I still can't get the packages page to work, even with a db backup from @abjerner so I will not be working on a PR for this one. So anyone reading this who can get the dev site to work properly, feel free to take this one.

**Comment by nul800sebastiaan** [comment]
@prjseal How come? Let's solve this. 🙂

**Comment by prjseal** [comment]
@nul800sebastiaan I rebased the repo, built it, let it install all of the npm packages etc, used @abjerner db backup and his migrations, ran the site, republished the site, rebuilt all of the indexes and still I can't view the packages page. It just shows as a 404. Custom errors are off so it's not hiding a 500 with a 404 error page message. Don't know what is wrong or where to start to solve it. @abjerner said it worked on his with master, but it doesn't on mine with master.

**Comment by abjerner** [comment]
@prjseal Didn't you also get some errors when going to the packages page in the backoffice? If so, posting the stack trace here might help determining what the culprit is.

**Comment by prjseal** [comment]
@nul800sebastiaan I already republished the entire site. 

I just ran the health check and got these errors.

![health check](https://i.imgur.com/trPYdq3.jpg)

**Comment by prjseal** [comment]
@abjerner I can get to the address 'https://our.localtest.me/umbraco#/content/content/edit/1113' now without an error since using your database, but I still can't view the page on the front end.

**Comment by poornimanayar** [comment]
PR in place https://github.com/umbraco/OurUmbraco/pull/425

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/425
