### ISSUE TITLE
Umbraco meetup.com groups

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#356]
I saw @ilhambo's [tweet](https://twitter.com/ilhamaa/status/1067381608049754113) from earlier today, and noticed that the list on Meetup.com has a lot fewer groups than in the file used on Our Umbraco: https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/config/MeetupUmbracoGroups.txt

Is this just while the groups from Our are still being added on Meetup.com (I see the list has grown with two since earlier today)?

If all groups are added to the Meetup.com organization, we could use that as the source instead of relying on the hardcoded TXT file we're currently using 😉

**Comment by ilhambo** [comment]
Hi Anders. The list on meetup.com is not complete as not all organizers have agreed to join. Also, there are some groups that haven’t been active in a long time so I’m in the process of reaching out to them to see if there is still interest in holding meetups. Hopefully, everyone will eventually join :)

**Comment by abjerner** [comment]
Thanks for the answer. I'll keep and eye on the list then and whether it makes sense to update the code at Our Umbraco 😉

**Comment by nul800sebastiaan** [comment]
For now, I've added the Nepal group! And for the foreseeable future we'll keep adding to that list, so I'll close this issue for now!
