### ISSUE TITLE
Comments disappearing

### ISSUE THREAD

**Issue by mortenbock** [umbraco/OurUmbraco#362]
I've experienced this a couple of times today. I added a comment, and when refreshing the page, it was no longer there.

I also received an email with a new comment from Shannon, but when following the link, it was gone:

https://our.umbraco.com/forum/contributing-to-umbraco-cms/94836-provider-model-for-search-and-indexing#comment-300079

I don't know if the actual comment is gone, or if it is missing from an index, or marked as spam somehow?

**Comment by nul800sebastiaan** [comment]
This is now fixed, it's a little silly: 

- We only have 2 levels of comments
- When someone comments on a second level comment normally, we set the parent Id to the 1st level comment
- However when we push a new comment into the DOM, it grabs the Id to set the parent to from the comment that was just added (the one that is highlighted and you're commenting on).
- This means that you're adding a comments to the THIRD level.. but there is not third level

So.. nothing disappeared, it was "just" not displaying correctly :-(

I've now put in a giant hack to fix that 😓 
https://github.com/umbraco/OurUmbraco/commit/284d7c6dad746bad8541098705058f4071953b50
