### ISSUE TITLE
Breadcrumb for the documentation is too dependent on the URL

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#363]
The breadcrumb for the documentation is based on the URL of each page, and therefore also reflects the casing of the URL. This may not be super important, but it differs from rest of Our, which uses lower case URLs.

As a versioned page is just another file, the name is also part of the URL - eg. `index-v8`. With this being part of the URL, it also shows up in the breadcrumb.

![image](https://user-images.githubusercontent.com/3634580/49529239-e20be700-f8b5-11e8-90b6-03da6dbb49ab.png)

A possible fix could be to build a sitemap of all pages - possibly also extracting the actual title from either the YAML or `<h1>` of each Markdown file. Any thoughts?

**Comment by nul800sebastiaan** [comment]
Thanks @abjerner - I think the Docs team is working on something like this already. Any feedback @jmayntzhusen ?

**Comment by jmayntzhusen** [comment]
We have been working on something similar with seo titles / descriptions, but we dont have anything for breadcrumbs for now. I agree that it could definitely be improved though, and that any "-v" filenames should be changed or removed from the breadcrumb to something better 🙂

**Comment by nul800sebastiaan** [comment]
Should the breadcrumb (in this case) just be "Content Apps (v8)"?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/416
