### ISSUE TITLE
Githib Master repository source does not match the live site?

### ISSUE THREAD

**Issue by readingdancer** [umbraco/OurUmbraco#377]
@nul800sebastiaan 

I assumed that the Master branch would represent the latest changes that are pushed up to the live site?

Currently an issue that I fix in #372 looks like it has been pushed live, but it's not been Merged into the Master branch and there are no other changes showing that would have fixed it.

Maybe it's been merged offline and not been pushed up to Github?

**Comment by nul800sebastiaan** [comment]
Not sure what you mean, it's definitely still the wrong link on live..


![image](https://user-images.githubusercontent.com/304656/51328420-a303b080-1a73-11e9-9529-1be693d4e4f0.png)
