### ISSUE TITLE
Adjust line height on releases overview

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#379]
On this page https://our.umbraco.com/download/releases/progress the line height is overwritten, which make the text a bit squeezed.

![image](https://user-images.githubusercontent.com/2919859/51471751-dac26f00-1d77-11e9-8e15-d4c0fdfbcea2.png)

Furthermore I think the parent element with `col-xs-6` should be changed to something like `col-xs-12 col-sm-6` so it use full width on mobile screens and "Features", "Issues" and "Breaking changes" are listed on separate lines.

![image](https://user-images.githubusercontent.com/2919859/51471823-12311b80-1d78-11e9-94db-5c3046b7080c.png)

**Comment by nul800sebastiaan** [comment]
Sounds good to me! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
