### ISSUE TITLE
Versions box needs z-index: 1

### ISSUE THREAD

**Issue by BatJan** [umbraco/OurUmbraco#382]
Going through a bunch of documentation I stumbled upon this issue, which I by mistake originally posted at the issue tracker for the documentation here https://github.com/umbraco/UmbracoDocs/issues/1461 - So the below is just copy/pasted directly and edited a bit.

**What type of issue is it?**
Other: Minor CSS bug

**What article/section is this about?**
[Dropdown](https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Dropdown)

**Describe the issue:**
The versions box needs position: relative and z-index: 1; since there otherwise is a risk that the headlines will lay on top of it. Try clicking the last "Current" link in the versions box in the above link - Currently not possible (On desktop at least) 😃

**Comment by nul800sebastiaan** [comment]
Thanks @BatJan ! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Jesper applied it and this is deploying now. 👍
