### ISSUE TITLE
Defaults for New Packages

### ISSUE THREAD

**Issue by hfloyd** [umbraco/OurUmbraco#383]
I haven't added a package in awhile, but recently I have noticed several packages which have "No current release" and no forum. It seems that there should always be a forum created by default for every package, and every package should require a current release.

example: https://our.umbraco.com/packages/backoffice-extensions/two-way-picker/

**Comment by nul800sebastiaan** [comment]
Yep, both would be excellent. The whole package creation process needs to be overhauled but making this the default would certainly be a good start!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
