### ISSUE TITLE
Update Gulp and all the client side build dependencies.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/OurUmbraco#384]
Gulp was using version 3.x and the latest version is currently 4.0 there were a lot of security vulnerabilities showing when you try and build the client side files.

Also the build script includes imagemin but is not using it, for some reason it is only compressing SVG images... twice!

Finally it is possible to run Gulp processes in Parallel, so assuming you have a multi-core machine you should see a performance increase in the build process.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/385

**Comment by readingdancer** [comment]
Closing the issue as it's now been merged in.
