### ISSUE TITLE
Add username and comment to package compatibility reporting

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/OurUmbraco#387]
When reporting on package compatibility, it should be mandatory to write a comment about what isn't working, along with the username. 

It would help package developers and others helping to find and fix any bugs, or dismiss the report, if it was made in error because of misunderstandings. 

It would also help others interested in using the package, as they might from the comment learn that the incompatibility warning is not relevant for their situation and be able to use the package anyway.

**Comment by nul800sebastiaan** [comment]
Hey @MichaelNielsenDK - this is an interesting request and I can certainly understand that it's frustrating not to know why there's negative reviews. However, this will also make the barrier even higher. Most people already don't leave a review at the moment, so adding requirements to reporting compatibility will make it even less likely that people will leave a review.

However, I think it would be helpful to make sure that each package always adds a forum for reviews, requests, bugs etc. https://github.com/umbraco/OurUmbraco/issues/383

In general the package section needs an overhaul in the future. For now I'll close this issue in favor of #383 which I think is an okay start at improving things a bit.

**Comment by nul800sebastiaan** [comment]
Hey @MichaelNielsenDK - this is an interesting request and I can certainly understand that it's frustrating not to know why there's negative reviews. However, this will also make the barrier even higher. Most people already don't leave a review at the moment, so adding requirements to reporting compatibility will make it even less likely that people will leave a review.

However, I think it would be helpful to make sure that each package always adds a forum for reviews, requests, bugs etc. https://github.com/umbraco/OurUmbraco/issues/383

In general the package section needs an overhaul in the future. For now I'll close this issue in favor of #383 which I think is an okay start at improving things a bit.

**Comment by MichaelNielsenDK** [comment]
It's true it would set the bar higher, but that would only strengthen and add value to the packages and the reporting system.

A report about a package not working is next to worthless for both other users and developers without any further information.
