### ISSUE TITLE
Umbraco 8 Package install, picks the Default Package not the v8 one

### ISSUE THREAD

**Issue by KevinJump** [umbraco/OurUmbraco#388]
Hi, 
_This might be a mixture of Umbraco 8 or our.umbraco.com Issue - so Just throwing this in, as it will be more of an issue as more packages are added._ 

You can't as a package developer mark two packages as current (one for v7, one for v8) - 
and in Umbraco 8 - when installing a package from the package section it picks the current one (not the v8.0 one) from the list of packages. 

**Either**
Our only lets you mark one package as current - so it might be that our has to let you mark active packages based on version. 

**or ?** 
Umbraco 8 doesn't look for the package from the list that is v8 so it might be that the package installer picks the correct package if there is one.

**Comment by nul800sebastiaan** [comment]
Yes, I know, I'll need to fix it in Our.

**Comment by nul800sebastiaan** [comment]
Oh @KevinJump .. ;-)

![image](https://user-images.githubusercontent.com/304656/52471115-5f8ef480-2b90-11e9-9f67-5eb68eedcfba.png)

I've fixed your latest uploads manually now, works!

![image](https://user-images.githubusercontent.com/304656/52471138-6e75a700-2b90-11e9-8683-bf71aa2f1e7f.png)

I've also updated the code, will roll out in the next few minutes. Thanks for reporting!

**Comment by KevinJump** [comment]
Woot! - so I created the package directly in Umbraco 8 (but more than happy to just edit the files now i've done that once) does that need some flag to make it put this value in?

**Comment by nul800sebastiaan** [comment]
Haha, I see what happened. Sorry, didn't mean to blame you, then it was totally us! ;-)

So we now create a package.xml with upper case "s" for "Strict" it looks like. Anyway, all fixed, Our understand any casing now and it won't be a problem in the future. Thanks very much for reporting! 👍 🏅

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/commit/3c68537bf1838447f1a575a1e746ff1243d646c9 by the way and was deployed immediately, so won't be a problem from now on!
