### ISSUE TITLE
Tweaking applying the new brand colours

### ISSUE THREAD

**Issue by leekelleher** [umbraco/OurUmbraco#397]
I assume this will ping you @nul800sebastiaan ... congrats on v8 launch and work done on new branding! 🚀 🎉 🌮 

I was looking at how the colours have been applied to Our Umbraco and wondering if it's worth me (and/or community) spending time to tweak them? (or is it something done in-house HQ, under the eye of creative direction?)

Tinkering around in devtools, I came up with this...
![capture](https://user-images.githubusercontent.com/209066/53412286-db76a280-39c0-11e9-8a87-244701194a6f.PNG)

Setting the navbar in sticky mode always, and changing the search bar to the pink (salmon/coral, whatever the correct name is for it).

**Comment by nul800sebastiaan** [comment]
Thanks lee! It was a quick and dirty job for now, but I'm sitting with mr. ClausK later this week to do some more tweaking, so don't spend too much time on it now.

**Comment by leekelleher** [comment]
Thanks @nul800sebastiaan! No problem-o, thought it best to check first! 👍 ❤️

**Comment by abjerner** [comment]
My first thought when I started scrolling (and the navbar disappeared), was that the site felt very "naked". I think Lee's suggestions would help fixing that.

But I'm sure Seb and Claus will cover that 👍

**Comment by nul800sebastiaan** [comment]
One could argue that the pink looks a bit "nude" though. 😅

**Comment by stevetemple** [comment]
You make that sounds like a bad thing
