### ISSUE TITLE
Bad url encoding in password reset emails

### ISSUE THREAD

**Issue by ItagMichael** [umbraco/OurUmbraco#398]
To reproduce:

1. Request a password reset with an email containing a '+' character
2. Receive an email with the following link:  https://our.umbraco.com/member/reset-password/?token=abc&email=me+our@example.com 
3. Follow it to be told Our "Can't reset your password with the provided information"

Solution:

Encode characters in the password reset URL. The following URL works: https://our.umbraco.com/member/reset-password/?token=abc&email=me%2Bour@example.com 

Additionally, the forgot password form asks for a username, but validates as an email, so it should probably be labelled email? The login form is labelled _Username_ too, but there is at least some text there that clarifies that it wants an email.

**Comment by nul800sebastiaan** [comment]
That's a bit annoying indeed! :-)


I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
