### ISSUE TITLE
Profile links to wrong member

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/OurUmbraco#399]
I assume it due to the "-" in the user name.

https://our.umbraco.com/members/Matthew-Wise/

**Comment by nul800sebastiaan** [comment]
Again? Stop updating your username! ;-)

**Comment by Matthew-Wise** [comment]
Am not sure it was fixed :)

**Comment by nul800sebastiaan** [comment]
Aah! Yes, I thought I fixed yours recently but I guess not! Good point, it has to be because of the `-`.

**Comment by abjerner** [comment]
@nul800sebastiaan can you confirm that https://github.com/umbraco/OurUmbraco/pull/375 is part of live? Both in the view and the rewrite rules?

I think I tested locally that my PR fixed the bug. If not, I can have another look at it 😉

**Comment by nul800sebastiaan** [comment]
Aaah yes, Anders fixed it, cool!  
Well.. unfortunately the web.config update didn't go through since we use the `.vsts.config` now haha. I'll fix it up now.

**Comment by nul800sebastiaan** [comment]
All fixed, enjoy your new and improved profile that actually shows YOUR info! ;-)
