### ISSUE TITLE
Packages page under profile is broken

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#401]
When navigating to your Our profile the left navigation has a menu item "Packages" which link to `/member/profile/packages/`.

![image](https://user-images.githubusercontent.com/2919859/53549519-a8552000-3b34-11e9-8509-0302add3059c.png)

However it seems this page in broken since it returns 302 Found and shows this page.

![image](https://user-images.githubusercontent.com/2919859/53549634-f9651400-3b34-11e9-90fe-97797019a8e8.png)

Btw. it would be great with a nice 404 and general error page (maybe with a unicorn or something else 🦄).

**Comment by nul800sebastiaan** [comment]
Thanks, related to the Cloud outage at the moment.

**Comment by nul800sebastiaan** [comment]
Ah nope, sorry different issue. No idea why yours doesn't work, mine does. 🤔

**Comment by nul800sebastiaan** [comment]
Some kind of null reference error on `GetListingsForContributor` - will get back to this later.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/412

**Comment by nul800sebastiaan** [comment]
This has been deployed now, did it work @bjarnef ?

**Comment by bjarnef** [comment]
@nul800sebastiaan well, I only see the "profile" link in left navigation, so I can't check what the previous "packages" link does?

![image](https://user-images.githubusercontent.com/2919859/56612412-a5e2e400-6614-11e9-9342-f8ac5c5f8e76.png)

**Comment by nul800sebastiaan** [comment]
@bjarnef That.. is very weird! It should just list the children of a certain node. What happens when you go to https://our.umbraco.com/member/profile/packages/ ?

**Comment by bjarnef** [comment]
@nul800sebastiaan on packages page it shows this.

![image](https://user-images.githubusercontent.com/2919859/56655044-fea49200-6691-11e9-9949-5afb52e42872.png)

On this page https://our.umbraco.com/member/profile/

![image](https://user-images.githubusercontent.com/2919859/56655186-62c75600-6692-11e9-80c0-f07d128b9440.png)

It was just the public profile page (available as link via right offcanvas menu)
https://our.umbraco.com/members/bjarnef/

Maybe the public profile should also have a page "packages" so community users can see which packages a member has created and contributes to?

**Comment by nul800sebastiaan** [comment]
Okay, so it works again, good!

Packages created is there, packages contributed to not yet, think there's a feature request for that already 

![image](https://user-images.githubusercontent.com/304656/56655541-60193080-6693-11e9-847d-10e824ffc193.png)

**Comment by bjarnef** [comment]
Yes, it does 👍 

Ahh, yes just need to scroll down the page 🙈
