### ISSUE TITLE
Set max width of images in project description

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#402]
In a project/package description it is possible to insert images, but these should probably be styled with `max-width:100%;` so it doesn't break the layout:
https://our.umbraco.com/packages/backoffice-extensions/svg-icon-picker/

![image](https://user-images.githubusercontent.com/2919859/53638056-4e805300-3c25-11e9-83a2-6c547138ddd9.png)

If I move the image up in the DOM it would looks like this:

![image](https://user-images.githubusercontent.com/2919859/53638046-46281800-3c25-11e9-9984-3548db2dcf71.png)

This would be nicer:

![image](https://user-images.githubusercontent.com/2919859/53638098-78d21080-3c25-11e9-9c1f-8c3da11979fa.png)

**Comment by nul800sebastiaan** [comment]
Sounds good, we'll need to do some parsing through HtmlAgilityPack I think.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
A quick solution is to add `max-width:100%;` on `img` element in this container.

**Comment by nul800sebastiaan** [comment]
Ah, even easier! Sounds good.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
