### ISSUE TITLE
Bringing the Contribute link back into Our Umbraco

### ISSUE THREAD

**Issue by jamiepollock** [umbraco/OurUmbraco#403]
Hey folks!
As part of the Umbraco Community Package Team, one of the actions we're looking to achieve is changing the Contribute link in the main navigation to go back into a page Our Umbraco rather than a github link.

The justification for this is there are many ways to contribute to Umbraco. Not necessarily just to the Core CMS but also to package development, docs, hosting a meet up, etc. 

Obviously from our point of view we're interested in guiding people to package development, if that's the correct course of action, but this could be a great hub for inspiring people on a multitude of ways of contributing to Umbraco & the Umbraco community.

Jamie

**Comment by jamiepollock** [comment]
The new [Umbraco Organiser Guide](https://github.com/umbraco/organizer-guide) might also be a good fit for a new contribute section too.

**Comment by nul800sebastiaan** [comment]
Hey Jamie! I am very happy for that, however I don't want to maintain a CONTRIBUTING.md on CMS and make sure it's in sync with the one on Our, so somehow we'll need to pull in the existing markdown files (both the high-level + detailed contribution guidelines) to the new contribution section. 

But yes yes yes, a hub would be great! If you're happy to work on that then I'm happy to guide you. :)

**Comment by jamiepollock** [comment]
@nul800sebastiaan sorry I'm so late in responding to this. Sounds great. I'll give it some thought and get back to the group on this news. Maybe between us we can get some ideas together.

**Comment by nathanwoulfe** [comment]
Re pulling the .md from GitHub - GH API has an endpoint to request individual files, and can have an accepts header set to return markdown as HTML. Can't remember the specifics, but it's pretty simple and would avoid duplication.

**Comment by nathanwoulfe** [comment]
Example in the GetDocs method here => https://github.com/nathanwoulfe/Plumber8/blob/master/Plumber.Core/Services/Implement/SettingsService.cs#L60

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
