### ISSUE TITLE
Mismatch between label and input

### ISSUE THREAD

**Issue by kjsguld** [umbraco/OurUmbraco#404]
Page in question: [https://our.umbraco.com/member/forgot-password/](https://our.umbraco.com/member/forgot-password/)

The label for the field asks for "Username", but validation asks for "Email address"

![image](https://user-images.githubusercontent.com/19648887/54339188-5fbd5c80-4634-11e9-8d0c-988208445f7c.png)

Reproduction steps: 
enter "username" in field

Fix: 
Change label to say "Email address"

**Comment by nul800sebastiaan** [comment]
Relates to https://github.com/umbraco/OurUmbraco/issues/398

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/412
