### ISSUE TITLE
Highlight requirements on download page

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#405]
Maybe the requirements should be highlighted a bit on the download page.
https://our.umbraco.com/download/

E.g. by using the red color in the logo.

```
.requirements {
    background: #f5c1bc;
    padding: 20px;
}
```

![image](https://user-images.githubusercontent.com/2919859/54341345-fa6c6a00-4639-11e9-86b1-5587db368e3b.png)

or a bit transparent (or with some white in the red color).

```
.requirements {
    background: rgba(245, 193, 188, 0.6); // #f9dad7;
    padding: 20px;
}
```

![image](https://user-images.githubusercontent.com/2919859/54341449-4cad8b00-463a-11e9-9cd1-1bb98c904fdf.png)

**Comment by nul800sebastiaan** [comment]
Thanks but that red just looks like: DANGER, DANGER.

I made it blue instead :)

![image](https://user-images.githubusercontent.com/304656/54342389-95feda00-463c-11e9-9895-c4378473508c.png)

**Comment by bjarnef** [comment]
Yeah, it the red has too much color. And an yellow background probably isn't better 😁

Not sure if there is a secondary color complementary to the blue color - I guess it can be too much blue on some pages, but let's keep the blue color for now 👍
