### ISSUE TITLE
Examine cannot index

### ISSUE THREAD

**Issue by tranphuongyd** [umbraco/OurUmbraco#414]
Hi everyone,

Today I get the issue when run search function, that using Examine API. However, yesterday it's work fine. 
![image](https://user-images.githubusercontent.com/7795756/54900599-769e6180-4f06-11e9-84a0-a199c3a2a2d3.png)

So I try to access the Examine Management in Umbraco CMS to check. then get the error: "The index cannot be read and will need to be rebuilt". After do rebuilt the search function worked.
Can you tell me the reason why I get this issue?

Thanks,
Phuong Tran

**Comment by nul800sebastiaan** [comment]
Hi there, make sure to get some help on the forum: https://our.umbraco.com
