### ISSUE TITLE
Link to release notes include double slashes

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#418]
On e.g. this page https://our.umbraco.com/download/releases/ the link the each release note include double slashes in url, e.g. https://our.umbraco.com/download/releases//801

Accessing the page via https://our.umbraco.com/download/releases/801 also work though.

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
