### ISSUE TITLE
Getting started link point at a 404

### ISSUE THREAD

**Issue by Tyriar** [umbraco/OurUmbraco#420]
Getting started link here: https://our.umbraco.com/download points at https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/.github/V8_GETTING_STARTED.md

**Comment by nul800sebastiaan** [comment]
Thanks, those links shouldn't have been there any more. 

Make sure to follow the documentation for install and setup guidance! https://our.umbraco.com/documentation/Getting-Started/Setup/Install/
