### ISSUE TITLE
Replace default package icon

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#422]
It would be great to replace the default package icon with either a font icon or SVG icon (SVG is probably preferable) with also these screen sizes and high screen resolutions nowadays.

![image](https://user-images.githubusercontent.com/2919859/56655998-a02ce300-6694-11e9-894f-e024530730ab.png)

https://our.umbraco.com/packages/

Maybe we should also have a separate property to select a package icon and so it not necessarily need to be listed with other screenshots. It could also make it easier to require a minimum image size of the package image/icon (maybe also allow to pick a SVG file). At the moment package icon is just the default screenshot image.

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
