### ISSUE TITLE
Suggestion: Don't accept gif's as avatars?

### ISSUE THREAD

**Issue by BatJan** [umbraco/OurUmbraco#426]
I just noticed that it's apparently possible to use a GIF for the avatar on the forum. Perhaps we should prohibit that? It's really distracting to look at imho - But maybe that's just me? 😃 See this post and spot the gif avatar 😉 https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/59693-Fetching-data-from-external-source

**Comment by nul800sebastiaan** [comment]
I think accepting gifs is fine.. but they should probably not animate. There's an imageprocessor option somewhere that only takes the first frame of the gif. Can't remember exactly what it is.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by BatJan** [comment]
Yes, I agree 😄

**Comment by bjarnef** [comment]
@nul800sebastiaan @BatJan something like this?
https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/animationprocessmode/

**Comment by nul800sebastiaan** [comment]
That's the one!

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by bjarnef** [comment]
@nul800sebastiaan I just notice this again on this https://our.umbraco.com/forum/using-umbraco-and-getting-started/105569-elasticsearch-and-umbraco-8-recommendations-for-integrating

But also took a bit of the focus here. Imagine several users here with animating gif avatars. Although very nostalgic and taking us back to the 90's, I think it can steal the focus 🚨🙈

https://our.umbraco.com/forum/using-umbraco-and-getting-started/105569-elasticsearch-and-umbraco-8-recommendations-for-integrating

**Comment by nul800sebastiaan** [comment]
Sure, if you want to work on it, the imageprocessor option to only show the first frame is still there 👍
