### ISSUE TITLE
Image gallery overlay not vertically centered

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#429]
In the image gallery on some projects/packages, it seems the opened image is not scaled to fit 100 viewport width and not centered vertically, when opening the gallery from mobile devices.

https://our.umbraco.com/packages/backoffice-extensions/umbraco-v8-back-office-themes/

![image](https://user-images.githubusercontent.com/2919859/57605354-c5f82a00-7566-11e9-905f-4fa4705b8b8c.png)

![image](https://user-images.githubusercontent.com/2919859/57605398-d6100980-7566-11e9-9d5b-6ba8e1434743.png)

while it does look fine on other pages.
https://our.umbraco.com/packages/backoffice-extensions/preflight-content-health-checks-for-umbraco-8/

![image](https://user-images.githubusercontent.com/2919859/57605493-08ba0200-7567-11e9-8bd1-2cef3358abe8.png)

**Comment by bjarnef** [comment]
At the moment it use fancybox v3.1.20, might be worth updating to latest v3.5.7 to see if it fix the issue or something else causing the issue.

**Comment by bjarnef** [comment]
It seem this issue happens when package description overflow the viewport width, e.g. with long links.
![image](https://user-images.githubusercontent.com/2919859/57606022-45d2c400-7568-11e9-9b74-3e805760efea.png)

Adding word-break seems to fx this issue.

```
.package-detail-content .package-detail-description {
    margin-bottom: 2rem;
    word-break: break-word;
}
```

![image](https://user-images.githubusercontent.com/2919859/57606103-7d417080-7568-11e9-8227-7f77e8f9d8ce.png)

**Comment by bjarnef** [comment]
Furthermore it should have a `max-width: 100%;` on images inside package description, otherwise there is a similar issue.
https://our.umbraco.com/packages/backoffice-extensions/svg-icon-picker/

![image](https://user-images.githubusercontent.com/2919859/57606253-d01b2800-7568-11e9-9411-07484743b626.png)

![image](https://user-images.githubusercontent.com/2919859/57606436-28522a00-7569-11e9-9ace-66622159ea86.png)

![image](https://user-images.githubusercontent.com/2919859/57606455-343dec00-7569-11e9-9fd3-bbe935c9c1cf.png)

**Comment by nul800sebastiaan** [comment]
👍

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by alikazai** [comment]
Thank @bjarnef for the information on this ticket i have created a PR https://github.com/umbraco/OurUmbraco/pull/441 for this hopefully all goes well. 
there was no way for me to test this on my repo as i the content on that page doesn't exist on the database, but hopefully the information you provided should be enough for this fix,.

Thank you

**Comment by bjarnef** [comment]
It also has issues when the package name overflow the viewport width. It should probably break word on a long package name.

**Comment by alikazai** [comment]
hi @bjarnef thanks for that. Unfortunately there was no way for me to test this on my repo as the content on that page doesn't exist on the database, that was provided by the OurUmbraco repo. hopefully @nul800sebastiaan can help solve this matter. 

In the meantime i will look into the package name issue and try get the resolved. 

Thanks

**Comment by bjarnef** [comment]
@alikazai I will recommend to create a PR and only commit the actual changed to fix the issue. It makes it much easier to review the code 🙂

**Comment by alikazai** [comment]
shall i remove the current PR then re add it with only the changed code

**Comment by bjarnef** [comment]
@alikazai you can always submit a new PR and close the existing one.

**Comment by alikazai** [comment]
ok

**Comment by nul800sebastiaan** [comment]
Hey @alikazai - sorry for the delay. Yeah, Our can be a bit hard to contribute to, sometimes you just have to play with the styles on the live site and take a guess at it 😄 

I'll have a look at the PR next week. I have some preliminary feedback: I can see that only 2 line in the css file have changed yet you checked in more changes. It will be much easier for us to review PRs that only contain the changes you actually made. Generally, we don't need to have cleanup tasks performed. 

That said, It's fine to leave the PR as it is, I'll update it when I get some time for it.

Thanks for having a look at it, much appreciated!

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/commit/e85ba1006043e426b29e3ed0e10393f064b3d9f9
