### ISSUE TITLE
Adding a new package is quite hidden away

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#430]
You have to click your avatar, then *Edit profile*, and then *Packages*:

https://our.umbraco.com/member/profile/packages/

Ideally there should be a more direct path - or at least more obvious. Eg. directly from the *Packages* section.

**Comment by nul800sebastiaan** [comment]
Yep.. :)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
