### ISSUE TITLE
Mobile navigation toggle is broken on mobile

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#439]
It seems the mobile navigation toggle is broken on mobile, but only in frontpage.

It is most likely a javascript error, note the hash in the url.

![Screenshot_20190525-123957_Chrome](https://user-images.githubusercontent.com/2919859/58368243-9fcd7500-7eea-11e9-8a04-70cc2e7949ab.jpg)

**Comment by abjerner** [comment]
This is a weird one. I don't get any errors (when emulating mobile on desktop), but still experience the same as you describe.

I think #440 would fix it though 😉

**Comment by bjarnef** [comment]
@abjerner it has happened after some of the recent changes.

**Comment by bjarnef** [comment]
There is a similar issue with the quick menu doesn't open on desktop, when clicking the user/avatar on frontpage. It does work on subpages though.

![image](https://user-images.githubusercontent.com/2919859/58544594-ddd7db00-8201-11e9-8f80-56de3a765feb.png)

**Comment by bjarnef** [comment]
and it seems the error in the Twitter partial are breaking part of the layout 🙈 

![image](https://user-images.githubusercontent.com/2919859/58544696-15468780-8202-11e9-8316-985902c59882.png)

**Comment by nul800sebastiaan** [comment]
The Twitter error has been fixed now, I'll close this one :)
