### ISSUE TITLE
Blog logo for Umbraco HQ gives 404

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#443]
![image](https://user-images.githubusercontent.com/3634580/59054871-e2049800-8894-11e9-83fb-c8ea7d70742a.png)

I had a look through the code, and the avatar/logo should be downloaded here:

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Community/BlogPosts/BlogPostsService.cs#L154,L166

I've tried to reproduce this locally, but everything works fine - so for now, I'm a bit unsure why the file isn't there.

Does the server know how to resolve it's own domain? If an exception is thrown, the message should be visible from the Hangfire log on the live server.

**Comment by nul800sebastiaan** [comment]
Not sure what happened but today it's magically working again.. I'll close this for now :-)

**Comment by abjerner** [comment]
Weird. It still happens here. Maybe we can convince Damiaan to teach us some magic?

**Comment by nul800sebastiaan** [comment]
lol!

So what is the "It" you're referring to?

Looks fine to me .. 

![image](https://user-images.githubusercontent.com/304656/59271414-0c1ed700-8c54-11e9-92c6-057e72fb12ec.png)

**Comment by abjerner** [comment]
The Umbraco logo refers to the following URL, which gives me a 404:

https://our.umbraco.com/media/blogs/6F278E68-C435-4DFF-A4EA-DB08835AB0F9.png?width=100&height=100&mode=max&upscale=true

(I even tried disabling my ad blocker, but nope)

**Comment by nul800sebastiaan** [comment]
🙈 

![image](https://user-images.githubusercontent.com/304656/59274027-c06f2c00-8c59-11e9-8fd2-6c83f0707cf1.png)

**Comment by abjerner** [comment]
Well ... now it also works here! Did you just fix something on the server?

(I swear it didn't work just before - I've even tested it on a few different computers)

**Comment by nul800sebastiaan** [comment]
I dunno.. it worked before your comment (https://github.com/umbraco/OurUmbraco/issues/443#issuecomment-500816300) as well.. haven't seen it broken to be honest.. Sounds scary, not sure what is going on!

**Comment by nul800sebastiaan** [comment]
And no, I didn't touch the server :-)
