### ISSUE TITLE
RSS feed for Umbraco is missing a permalink

### ISSUE THREAD

**Issue by greystate** [umbraco/OurUmbraco#446]
## Problem
I don't really know if this is the correct place to file this bug, but here goes:

The RSS feed for Umbraco's [official blog on umbraco.com](https://umbraco.com/blog/) does not include a permalink for the entries, which means you can't jump from an RSS reader application to the post on the blog.

## How does it make you feel?
It makes me feel so so sad 😢

**Comment by nul800sebastiaan** [comment]
I'll send this off to the team who build the website! 👍 

This is not the right place but I also don't know what would be really ;-) 

When this is fixed I'll ask them to update here, thanks!

**Comment by hartviglarsen** [comment]
Hi @greystate 

Sorry for the delay on this - I have been on vacation. :) 

I've fixed the issue and will roll out the fix tomorrow.
