### ISSUE TITLE
Meetup integration will not work beyond August 15

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#448]
Just a little heads up. Our is currently using an API key for accessing the API. This will not be possible after August 15.

The Meetup integration should then instead use OAuth 2. I'll look into creating a PR for that so this is ready at least some time before August 15.

![image](https://user-images.githubusercontent.com/3634580/59519721-c3bc1f00-8ec8-11e9-835f-e0190deac887.png)

**Comment by nul800sebastiaan** [comment]
Yikes! Thanks for the help, let me know what I need to do to generate an authorization token.

**Comment by abjerner** [comment]
Well, I think we actually might be safe already. When I submitted this issue, it was because I had found this file:

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Events/Meetup/MeetupController.cs

For starters I was a bit confused why it didn't use my Meetup package, and when I had another look today, I realized that this code is back from 2015. @nul800sebastiaan do you know whether this is actually still used anymore?

It seems to be used by this file (which again I'm not sure is used anymore):

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Events/Api/EventsController.cs#L129

The current implementation of meetups in the community sections uses this class from my PR last year:

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Community/Meetup/MeetupService.cs

As part of the code states, we're actually neither using OAuth or an API key as what we're doing doesn't require any authentication:

```
// Initialize a new service instance (we don't specify an API key since we're accessing public data) 
var service = new Skybrud.Social.Meetup.MeetupService();
```

As far as I can tell from their email, they're not changing anything for unauthenticated access to the API. Still, it may probably be a good idea to create an OAuth app should be need this later (although HQ has a pro account right?).

**Comment by abjerner** [comment]
Due to the right circumstances around how we use the Meetup API, we weren't affected by the changes. So probably about time to close this issue.
