### ISSUE TITLE
Browse most popular packages title is wrong

### ISSUE THREAD

**Issue by prjseal** [umbraco/OurUmbraco#449]
When you go to the packages page without any query string you see a title like this:

## Browse most popular packages

This is incorrect, because you are looking at the latest packages not the most popular, which can be misleading for people.

So it should look like this by default instead:

## Browse latest packages

I have created a PR which I will link to this issue.

**Comment by nul800sebastiaan** [comment]
Thanks @prjseal ! Will have a look at it this week! 👍

**Comment by prjseal** [comment]
Any joy with this one @nul800sebastiaan ?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/450
