### ISSUE TITLE
Could not load file or assembly umbraco I.m using Umbraco CMS with gitHub and I get this error when it runs Could not load file or assembly 'App_Web_all.generated.cs.8f9494c4.dkciotxm, Version=0.0.0.3, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### ISSUE THREAD

**Issue by valdaniocpc** [umbraco/OurUmbraco#453]
I.m using Umbraco CMS with gitHub and I get this error when it runs 
Could not load file or assembly 'App_Web_all.generated.cs.8f9494c4.dkciotxm, Version=0.0.0.3, Culture=neutral, PublicKeyToken=null' or one of its dependencies. O sistema não conseguiu localizar o ficheiro especificado.

**Comment by nul800sebastiaan** [comment]
Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by valdaniocpc** [comment]
ok! Thank you so much.
