### ISSUE TITLE
Screenshots have black background

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#455]
I noticed our.umbraco.com has been upgraded to v7.15.0 and that it seems screenshots now have black background although `bgcolor=fff` is specified.

![image](https://user-images.githubusercontent.com/2919859/61189600-1b000b80-a690-11e9-87d1-09ea594c1b70.png)

![image](https://user-images.githubusercontent.com/2919859/61189606-22bfb000-a690-11e9-9bd0-018bbadf65da.png)

![image](https://user-images.githubusercontent.com/2919859/61189612-3408bc80-a690-11e9-87b5-219a5bf4e85d.png)

This also affect the screenshots shown in packager in Umbraco backoffice.

![image](https://user-images.githubusercontent.com/2919859/61189618-500c5e00-a690-11e9-9d4e-4107ba03e3c4.png)

![image](https://user-images.githubusercontent.com/2919859/61189625-64e8f180-a690-11e9-90a7-f8489acd3338.png)

**Comment by nul800sebastiaan** [comment]
Apologies for the delay, this should now be fixed in revs https://github.com/umbraco/OurUmbraco/commit/695e7d56231abab4cbb3caba7a7e666df0f8e445 and https://github.com/umbraco/OurUmbraco/commit/aa9e22d9b617fd4662a48eadffce16c1ab42e728
