### ISSUE TITLE
Avatars missing on our

### ISSUE THREAD

**Issue by soreng** [umbraco/OurUmbraco#456]
https://our.umbraco.com/

![image](https://user-images.githubusercontent.com/359492/61284234-d7f08600-a7be-11e9-9bdb-ee08661ed0c4.png)

The avatars are missing - seems the remote.axd handler does not handle the remote content (?). Maybe some settings allowing a domain, maybe domain changed?

**Comment by nul800sebastiaan** [comment]
Apologies for the delay, this has now been fixed in rev https://github.com/umbraco/OurUmbraco/commit/4d99ce2c7134902a5fcbbb06db415915d186571b
