### ISSUE TITLE
I cannot get the preview badge to show on preview pages

### ISSUE THREAD

**Issue by hamzatki** [umbraco/OurUmbraco#467]
Hi,

I have 2 versions of umbraco installed (7.13.2 and a 7.13.2  upgraded to 7.15.2) on my machine. 

I cannot get the preview badge to work on both 7.13.2 and 7.15.2.

I have this element on umbracoSettings.config 

 <PreviewBadge>
      <![CDATA[
      <a id="umbracoPreviewBadge" style="z-index:99999; position: absolute; top: 0; right: 0; border: 0; width: 149px; height: 149px; background: url('{0}/assets/img/preview-mode-badge.png') no-repeat;" href="#" OnClick="javascript:window.top.location.href = '{0}/preview/end?redir={1}'"><span style="display:none;">In Preview Mode - click to end</span></a>
    ]]>
    </PreviewBadge>

and also added this to the homepage razor page.

@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;

**Comment by nul800sebastiaan** [comment]
Hey there @hamzatki - make sure to get some help on the forums at https://our.umbraco.com 👍
