### ISSUE TITLE
Not receiving notifications from forums.

### ISSUE THREAD

**Issue by skartknet** [umbraco/OurUmbraco#472]
I don't get any notifications for new message in the forums I follow or for responses to my posts.
I have checked my settings and they look correct:
![image](https://user-images.githubusercontent.com/1685262/64929059-4c4db100-d864-11e9-8a2e-c64906ffca46.png)

Not sure If I have to do anything else...?

**Comment by nul800sebastiaan** [comment]
Do you get any email from Our? If not it could be that something is marking them as spam for you or the emails are bouncing or something.

**Comment by skartknet** [comment]
Nope, nothing in the spam folder. Is there anyway I can test it? I receive messages if I want to reset my password for instance.

**Comment by nul800sebastiaan** [comment]
Hmm, yeah I can see no outgoing mails for you after creating a new topic (I've also deleted it again already). 

Is this "Follow" button green for you?

![image](https://user-images.githubusercontent.com/304656/64943754-e154a800-d86c-11e9-8d25-2eb60f08eff2.png)

**Comment by skartknet** [comment]
Actually I have received a notification:

![image](https://user-images.githubusercontent.com/1685262/64948023-86956d80-d8b9-11e9-8b92-fa09a3bca360.png)

Before you post I had unfollowed and re-followed the forums. Maybe that has fixed it? ¯\_(ツ)_/¯

We can close this for the moment if you like an I'll reopen it if I see it fails again.

**Comment by nul800sebastiaan** [comment]
Haha! That is so weird! Yep, I also see now Sendgrid has delivered the mail successfully. 

Alright, let's close it for now and chalk it up to a fluke!

**Comment by skartknet** [comment]
Thanks for your help Sebastiaan.
