### ISSUE TITLE
Image size of Twitter avatars

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#473]
Is it possible to increase the image size of the Twitter avatars? At the moment they are a bit blurry compared to the user avatars on Our.

![image](https://user-images.githubusercontent.com/2919859/65125190-75517b80-d9f5-11e9-8f53-ae654d4c8f98.png)

![image](https://user-images.githubusercontent.com/2919859/65125242-7aaec600-d9f5-11e9-9960-3e8a4fd8db74.png)

**Comment by nul800sebastiaan** [comment]
Sure thing, fixed now.

**Comment by bjarnef** [comment]
Yeay, you look so much sharper now Seb! 😉 

![image](https://user-images.githubusercontent.com/2919859/65148008-99c24d80-da1f-11e9-8ef0-7b6cefee99a8.png)
