### ISSUE TITLE
The categories for forum posts are outdated

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/OurUmbraco#474]
Regarding the following tweet:

https://twitter.com/peteduncanson/status/1176429154700537856?s=20

![image](https://user-images.githubusercontent.com/304656/65520683-4735d500-dee8-11e9-8ba3-1a7f4bd5c24d.png)

We've noticed over the last few years that forum categories  (in general) are completely confusing to people and more often than not are selected wrong. Therefore, we believe it is time to retire categories (other than forums that are specific to packages).

We'll still require people to select an Umbraco version when posting questions but other questions are just general Umbraco questions for now. In the future it could be interesting to experiment with automatic tagging, maybe using cognitive services. That way the onus for categorizing correctly is not on the person just trying to figure out how to fix their current problem.

**Comment by nul800sebastiaan** [comment]
Fixed in 827835b15a0b237940ba58e8a1a08fe5e80b071f

**Comment by leekelleher** [comment]
@nul800sebastiaan Has one of the categories been renamed? As I think it's caused a 404.
Original URL from Pete's tweet: https://our.umbraco.com/forum/using-umbraco-and-getting-started/99209-content-randomly-unpublished-any-ideas ... returns a 404.

Whereas using the updated category slug is working fine: https://our.umbraco.com/forum/using-umbraco/99209-content-randomly-unpublished-any-ideas

Might need a rewrite rule to save the google juice?

**Comment by nul800sebastiaan** [comment]
@leekelleher Interesting.. good catch, I did rename that one! I'll see why there was no redirect created tomorrow, renamed it back for now, thanks for the hint!
