### ISSUE TITLE
No <title> value for the main documentation page

### ISSUE THREAD

**Issue by abjerner** [umbraco/OurUmbraco#479]
https://our.umbraco.com/documentation/

![image](https://user-images.githubusercontent.com/3634580/65916983-b161e480-e3d6-11e9-8095-500677ccab8e.png)

![image](https://user-images.githubusercontent.com/3634580/65916999-b888f280-e3d6-11e9-8de7-6ade798c1591.png)

Strangely it works fine when I run the latest code on my local machine. 😮

**Comment by nul800sebastiaan** [comment]
Hmmm, that is a weird one! Do you have any idea where it's being set on that template?

**Comment by abjerner** [comment]
At least on my machine the <title> value is generated by this line:

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/Views/DocumentationSubpage.cshtml#L71

I tried importing the newest docs right before testing, but perhaps the live site runs the code for the `if` instead of the `else` block:

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/Views/DocumentationSubpage.cshtml#L13

Maybe I'm missing something else causing my machine to run the `else` instead of the `if` block 😮

**Comment by jmayntzhusen** [comment]
Seems to be there now when I test - the YAML override was added in https://github.com/umbraco/UmbracoDocs/pull/1953, so I guess we can close this one for now 🙂
