### ISSUE TITLE
Documentation menu overflowing bottom options

### ISSUE THREAD

**Issue by skartknet** [umbraco/OurUmbraco#480]
When navigating the docs, if you select one of the pages with multiple subpages, these are revealed pushing the bottom options down. There's a point where the menu can't fit any more options and they are hidden. (Argh! I don't know how to explain!) Basically the menu doesn't expand enough.

This is a capture with all the options (nothing wrong here):
![image](https://user-images.githubusercontent.com/1685262/65938481-61caf980-e466-11e9-941d-8e3b4b6bb00e.png)

Clicking on 'Templating' makes the bottom options (Mapping and Scheduling) overflow:
![image](https://user-images.githubusercontent.com/1685262/65938550-950d8880-e466-11e9-8edf-83b0e14846b6.png)

**Comment by nul800sebastiaan** [comment]
Gosh, I guess we shouldn't put so much documentation up! 🙈 

Not sure if we have a hardcoded max height or something 🤔

**Comment by liamlaverty** [comment]
Was this fixed by https://github.com/umbraco/OurUmbraco/pull/493 ? I was going to take a look at it, but I can't recreate it now.

**Comment by nul800sebastiaan** [comment]
Ah yes it was @liamlaverty - thank you! I forgot to close this one! 👍
