### ISSUE TITLE
Unify Search on /packages with the one shown in the backoffice of umbraco

### ISSUE THREAD

**Issue by KevinJump** [umbraco/OurUmbraco#554]
At the moment the packages page on our is not using the same search as that used for the feed to the back office packages. we should unify them. 

in short we should make the packages page use the `PackageRepositoryService`

**Comment by KevinJump** [comment]
Looking at this, it appears that the PackageRepositoryService returns packages which are retired. (e.g image processor in collaboration tools).

So just to confirm we should also fix that ?

**Comment by jmayntzhusen** [comment]
Closing as the PR is merged, missed this issue at the time 🙂
