### ISSUE TITLE
Link to database backup in readme not working

### ISSUE THREAD

**Issue by markwemekamp** [umbraco/OurUmbraco#591]
The link in the readme file to the database backup seems to be outdated

https://umbracoreleases.blob.core.windows.net/ourumbraco/OurDev20200107.7z gives me a 404 error

**Comment by nul800sebastiaan** [comment]
Yep. We're working on it, might take a little while longer though, it's not an easy process to generate a new version unfortunately! :-)

**Comment by AaronSadlerUK** [comment]
I didn't spot this issue until after opening mine.

Any eta on this, I wanna play with the site :)

**Comment by nul800sebastiaan** [comment]
Working on it still, shouldn't be long now I hope 🤞

**Comment by nul800sebastiaan** [comment]
A little longer than expected, but the dev database is now back Also note the default branch has been renamed from master to main, easiest way to deal with that is to do a fresh fork and clone if possible! 🙂
