### ISSUE TITLE
Allow package owners to mark answers for package forums

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/OurUmbraco#592]
If you are a package dev and you've create a forum on your package, it would be great if we could have the power within our own forums to mark replies as answers.

We get a lot of support requests which we do provide the answer the OP was needing but they tend to forget or miss marking the thread as having an answer.

As the owner of the forum, it would be great if we could mark the answer ourselves in these situations so that our support forums don't look like they are full of unanswered questions.

**Comment by nul800sebastiaan** [comment]
Thanks @mattbrailsford - fixed in https://github.com/umbraco/OurUmbraco/commit/fb64c34a3ffc2c9c4be52b71a408dc08372d1965

This is now deployed and live.

Note that we do send people reminder emails to mark their questions as solved, so maybe don't mark them as such too quickly! 😄

**Comment by mattbrailsford** [comment]
🎉🎉🎉🎉

That's awesome!

What's the timeframe on those emails? Just so we know after what timeframe we can go mark answers?

A longer term goal could probably to send another email to package owners a little after the one to the OP so we could just be reminded after an appropriate time, but this is an ideal. Just being able to mark them is fantastic.

Thanks @nul800sebastiaan

**Comment by nul800sebastiaan** [comment]
It's pretty long at the moment, 7 days after the last activity on the topic to give people a chance to try out the replies.

Sure, a reminder can probably be made like this one we already have: https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/NotificationsCore/Notifications/ScheduleHangfireJobs.cs#L22

PRs welcome!
