### ISSUE TITLE
Not getting any emails anymore

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/OurUmbraco#595]
Hey, appaers that I'm not getting any emails from our anymore since around April...

So notifications, pw resets...

Cheers,
Tim

**Comment by nul800sebastiaan** [comment]
Looks like your email server had a problem around late April:

![image](https://user-images.githubusercontent.com/304656/86094738-389ccf80-bab1-11ea-9c9a-4e794fd08857.png)

Which happened often enough for the mail server to not try again:

![image](https://user-images.githubusercontent.com/304656/86094775-43576480-bab1-11ea-8824-89c2b2a8fff8.png)



Fixed now!

**Comment by TimGeyssens** [comment]
Awesome, thanks
