### ISSUE TITLE
Link to packages from the profile window

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/OurUmbraco#633]
To save a few clicks (I know I'm lazy right?), I think adding a link to the window which shows when you click the profile icon, to take you to your packages would be mighty useful :)

**Comment by LottePitcher** [comment]
Hey Aaron, great minds think alike! There's already an issue over on the Package team repo for this:
https://github.com/umbraco/Umbraco.Packages/issues/65

Hopefully we'll see this get done soon!

**Comment by AaronSadlerUK** [comment]
@LottePitcher Just submitted a pull request 👍 

#634

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/634
