### ISSUE TITLE
Any plans to migrate to Umbraco v8.x?

### ISSUE THREAD

**Issue by sixeyes** [umbraco/OurUmbraco#653]
Looking for a forum package for Umbraco. This looks like the best candidate but is using v7.x
Are there any plans to migrate to Umbraco v8.x?

**Comment by nul800sebastiaan** [comment]
This is absolutely not a good candidate! 😅 🙈  _seriously, our forum is cobbled together, it works.. and that's about it_

I'm not aware of any forum packages for v8 and I would say it's very specialized and shouldn't be handled with Umbraco.  
There's so many things to think about, spam, emails, upvoting, downvoting, culture, moderation, etc. I think [Discourse](https://www.discourse.org/) is excellent and they are in the business of making forum software. I know it's not integrated in Umbraco but I would recommend having a look at it.
