### ISSUE TITLE
Avatars not always shown for contrib badge

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#671]
On download page like this https://our.umbraco.com/download/releases/8110 it seems avatars not always is shown for contrib badges using the avatar of the GitHub user (or maybe the avatar from the Our profile which has the GitHub profile linked?)

![image](https://user-images.githubusercontent.com/2919859/104568403-58ac6e80-5650-11eb-89b9-69026eee9d54.png)

![image](https://user-images.githubusercontent.com/2919859/104568745-c062b980-5650-11eb-9231-78e39748f1f6.png)

**Comment by nul800sebastiaan** [comment]
That's mostly because @NathanWoulfe refused to add the `community/pr` label! 😛 I correct all the labels before a release anyway, and the avatars are now showing for all community contributions.

**Comment by nathanwoulfe** [comment]
Yup, I've heard he's very difficult to work with.
