### ISSUE TITLE
Avatars not shown for GitHub Contributions

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#676]
It seems the avatars on home page at the moment isn't shown:

![image](https://user-images.githubusercontent.com/2919859/105488547-14ede080-5cb2-11eb-8487-5503cb75c779.png)

However e.g. the image on GitHub does seem to be available: https://avatars.githubusercontent.com/u/2919859?v=4
The image url here throw 404 though: https://our.umbraco.com/remote.axd?https://avatars.githubusercontent.com/u/2919859?v=4?width=112&upscale=true

**Comment by nul800sebastiaan** [comment]
Thanks! Weird they started using the non-numbered URLs now for user content.. anyway, fixed now https://github.com/umbraco/OurUmbraco/commit/6d9e2c734936dd6a753d004ff2b4830ac036dfb5
