### ISSUE TITLE
C-Trib page not updating?

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/OurUmbraco#680]
Just spotted than even though I have several Our and now a Core PR merged, I do not show on the C-Trib  page:

https://community.umbraco.com/get-to-know-the-community/badges/

Not sure where the issue lies, my account uses my Github to login.

**Comment by nul800sebastiaan** [comment]
You didn't have a `c-trib` badge yet, but do now!
![image](https://user-images.githubusercontent.com/304656/109159321-c4681800-7774-11eb-81c5-0225221a77c4.png)

Not sure how heavily that page is cached but now that you have the badge it should update at some point! 😅

**Comment by AaronSadlerUK** [comment]
Thanks @nul800sebastiaan

**Comment by nul800sebastiaan** [comment]
There you are!

![image](https://user-images.githubusercontent.com/304656/109171888-7ce88880-7782-11eb-909f-0ca5198f4951.png)

**Comment by AaronSadlerUK** [comment]
🥳🥳
