### ISSUE TITLE
Can't make a package a live

### ISSUE THREAD

**Issue by skttl** [umbraco/OurUmbraco#688]
I'm trying to release a new package, and I created a draft of the package, in order to have somewhere that UmbPack could post the file.

But after the build completed, and the file was uploaded I can't make the package live? When I check the box and click next, I just get redirected to the same page, with "Make live" unchecked.

I also noticed that the package file is not set to be current, and nothing happens when clicking "Make current".

Package id is 287538 if you need that :)

**Comment by skttl** [comment]
And then I just went and tried again - now it works 🙈

**Comment by nul800sebastiaan** [comment]
Thanks @skttl - sorry about that, it's not you, it's us! 😅 Doing some server maintenance now..
