### ISSUE TITLE
Link from upgrade notification in Umbraco no longer compare changes

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#712]
In Umbraco when a new version is ready you will see a upgrade notification, which is linking to, e.g. the following URL:
https://our.umbraco.com/download/releases/8141?version=8.9.0

Previous this compared the two versions and listed changes between the current and latest version, but this seems no longer to be the case?

**Comment by bjarnef** [comment]
It seems we have this 
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Install/InstallSteps/UpgradeStep.cs#L44

E.g.
https://our.umbraco.com/download/releases/compare?from=8.9.0&to=8.14.1&notes=1

But not the same as used in the notification here I guess.

**Comment by bjarnef** [comment]
I guess it may always have link to release page here: https://our.umbraco.com/download/releases/8141?version=8.9.0 .. it doesn't seem the version querystring has any effect though, but maybe used for tracking/stats?

**Comment by nul800sebastiaan** [comment]
Maybe it was used in the olden days for tracking, don't think it's used in tracking any more. But let's just leave it, it doesn't hurt! :)
