### ISSUE TITLE
Install command on project page

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#720]
I noticed the NuGet install commands has been updated on Our for packages working on Umbraco v9.

![image](https://user-images.githubusercontent.com/2919859/129533943-69badf79-4842-4d5f-87ee-d12b043b6a43.png)

While Umbraco v8 package still shows `Install-Package` command.

![image](https://user-images.githubusercontent.com/2919859/129533988-a064e690-2322-486b-9a16-0dac6d79d224.png)

However some packages works both on v8 and v9.
E.g. the The Starter Kit doesn't show the install command on v8 and soon Vendr should also be available for v9.
https://our.umbraco.com/packages/website-utilities/vendr/

Should it show both install command to v8 and v9 if supported on both versions?

**Comment by nul800sebastiaan** [comment]
Ah.. yeah, sure. On my list.
