### ISSUE TITLE
Avatars are squeezed on community site

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#723]
## Detailed description
Not specific an issue on Our, but on https://community.umbraco.com/learn-about-the-community/karma-leaderboard/ where Community menu item on Our links to https://community.umbraco.com/

Feel free to report this to the right team and close this if there's another place this should be reported 😁

It should probably crop the image first and scale would be ideal too, so it doesn't load an image of 1500 × 1125 px 😅

![image](https://user-images.githubusercontent.com/2919859/129890245-bda9f194-6b91-4bf7-b10f-8b7cb47c3ffc.png)

Alternatively it could use the cropped image from Our: https://our.umbraco.com/media/upload/559936fe-4ff0-45f3-857a-115a6bc80f65/_MG_9991.jpg?width=100&height=100&mode=crop&upscale=true

**Comment by OussamaSALAHOUELHADJ** [comment]
Hey @bjarnef, can you assign this issue to me.

**Comment by bjarnef** [comment]
@OussamaSALAHOUELHADJ I don't have access to that feature in this repository, but you are welcome to have a look.
I guess there is a private repository for the https://community.umbraco.com/ site.

**Comment by OussamaSALAHOUELHADJ** [comment]
@bjarnef so I just need to fork this repo and work on the issue?

**Comment by nul800sebastiaan** [comment]
No it's not possible to fix, it's happening in a private repo.

**Comment by OussamaSALAHOUELHADJ** [comment]
Ok, I see what you mean, just to help you, i think it is a simple bug:
the image request must have a query string parameters for the height and the width.

**Current request:**
`https://our.umbraco.com/media/upload/*{IMAGE_ID}*.jpeg`

![image](https://user-images.githubusercontent.com/55297866/135814428-ac4d0d28-2360-456b-bff4-33f2fecfa7e8.png)


**Must be:**
`https://our.umbraco.com/media/upload/{IMAGE_ID}.jpg?width=125&height=125&mode=crop&upscale=true`

![image](https://user-images.githubusercontent.com/55297866/135814557-cbcc8c23-9a7f-48e0-8c41-7cb8962ad46a.png)

**Comment by nul800sebastiaan** [comment]
Thanks, yep, we're working on it. :)

**Comment by nul800sebastiaan** [comment]
This has now been fixed, thanks for reporting!

**Comment by bjarnef** [comment]
@nul800sebastiaan speaking about the community site I noticed the HQ badge on Our no longer link correct, e.g. from Warren here: https://our.umbraco.com/packages/website-utilities/our-umbraco-taghelpers/

The HQ badge link to https://community.umbraco.com/umbracians-in-action/badges/#hq .. the page was probably moved. Btw. a nicer 404 would be great 😁
