### ISSUE TITLE
Package version badge issue when supporting v9

### ISSUE THREAD

**Issue by adamhearn** [umbraco/OurUmbraco#726]
The package summary displayed when browsing packages on Our does not show support for version v9 in the version badge.

## Detailed description

I've updated my package to support the v9 release and as my package is back-end only, the v9 provision is via NuGet only. The summary only shows badges for v7.15 - v8.15 (as they were provided as both NuGet and zip files). The package does appear when filtering for Version 9 as per:

![image](https://user-images.githubusercontent.com/13589850/135220593-70947f2d-fe2c-48c6-810e-41f4dd53b569.png)

I've enabled the "This package is in the new (v9+) NuGet format" option and the package detail page correctly shows this:

![image](https://user-images.githubusercontent.com/13589850/135220413-73e97d7b-7f8f-4306-b72e-f1e5dd13fcc8.png)

There doesn't seem to be a way of marking the version outside of uploading a zip [containing nupkg file] and checking the appropriate versions from the list? 

My package: https://our.umbraco.com/packages/backoffice-extensions/scheduled-content-dashboard/

**Comment by nul800sebastiaan** [comment]
Thanks! Looking better now: 

![image](https://user-images.githubusercontent.com/304656/135294076-6b8e2b77-cb34-43a6-9424-53760fe8ba6b.png)
