### ISSUE TITLE
Umbraco logo missing on blog posts

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/OurUmbraco#734]
Checked out the blog posts page today and noticed that the logo for the Umbraco posts are missing:
![image](https://user-images.githubusercontent.com/11466511/139661172-eb591264-f7e7-4f73-a702-d6b182207e25.png)

Not quite sure where the image configuration comes from, but is probably an easy fix somewhere

**Comment by nul800sebastiaan** [comment]
Hmmm, they work for me (or.. maybe they work now and didn't before, don't know!). If they stop working again for you, please note the URL and see if you can find anything interesting in the network tab of your browser's F12 tools!

![image](https://user-images.githubusercontent.com/304656/139674805-4a5532b9-ad4b-4dff-96c7-6b3ac7ea08cd.png)

For now, I'll close this one but we can re-open if it happens again and we have something to investigate on. 

Thanks @patrickdemooij9!

**Comment by patrickdemooij9** [comment]
@nul800sebastiaan, that is interesting. It is still not working for me. This is the url that is currently giving a 404 for me: https://our.umbraco.com/media/blogs/6F278E68-C435-4DFF-A4EA-DB08835AB0F9.png.
Also tried it in incognito in case one of my chrome extensions was blocking the image for some reason, but they also won't load there.

**Comment by patrickdemooij9** [comment]
Oke, this is really strange. If I change the upper case letters to lower case, then the image does work for me: https://our.umbraco.com/media/blogs/6f278e68-c435-4dff-a4ea-db08835ab0f9.png.
So the link above here does show me an actual image while the other one just shows me a 404.

**Comment by patrickdemooij9** [comment]
And now when I refresh the page, it all works... I guess I'll just blame this on the magic of the internet.
![image](https://user-images.githubusercontent.com/11466511/139676064-f3e4ffb9-6c07-468f-b577-70897c7e0b2f.png)

**Comment by abjerner** [comment]
I recall chatting with @nul800sebastiaan about this, and it's apparently a temporary thing as it comes and goes a bit at random.

As it ended up working the last time I tested it, I haven't looked further into finding the culprit. But it's been an issue for a while.
