### ISSUE TITLE
Documentation page breaks with querystring

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#759]
## Detailed description

The community site https://community.umbraco.com/ links to "Documentation" section on Our

![image](https://user-images.githubusercontent.com/2919859/159095043-e6e78b4f-4611-4042-9abd-e62b74a4ab5b.png)

The URL https://our.umbraco.com/documentation/ works, but the documentation site links with a querystring: https://our.umbraco.com/documentation/?_ga=2.58184105.2090058464.1647427182-609372253.1646231368

which result in: https://our.umbraco.com/error/?aspxerrorpath=/documentation/

![image](https://user-images.githubusercontent.com/2919859/159095136-e15df809-e488-4099-ac63-260153a0e411.png)

In fact any querystring breaks, eg. https://our.umbraco.com/documentation/?v=1 or https://our.umbraco.com/documentation/?umbraco=rocks

It only seems to be an issue specific to the documentation page on Our.

**Comment by nul800sebastiaan** [comment]
Thanks noticed that one as well, this is now fixed. 👍
