### ISSUE TITLE
Login with GitHub is showing Authentication error

### ISSUE THREAD

**Issue by sophie-neale** [umbraco/OurUmbraco#770]
The login with GitHub functionality has broken.

If a user selects Login with GitHub from https://our.umbraco.com/member/login/ there is a long wait and then the attached error message is shown. 
<img width="1851" alt="log in" src="https://user-images.githubusercontent.com/35264991/170968336-975ee381-db18-404e-857a-5d97f41774dc.png">
<img width="1600" alt="error" src="https://user-images.githubusercontent.com/35264991/170968346-0e8fdad7-04c6-4290-adbb-07189e39b31b.png">

**Comment by bjarnef** [comment]
I had the same issue. Second time it was a bit slow, but then worked. And on subsequent attempts it seemed to be faster (I guess it may be cached).

**Comment by nul800sebastiaan** [comment]
Thanks for reporting! We were doing some intense database work at the time and it seems like the resources ran out, I'll make sure to make our SQL instance a bit larger next time we do some heavy database work. 👍
