### ISSUE TITLE
Umbraco version dropdown in package directory missing v10

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/OurUmbraco#781]
Umbraco 10 is not included in the version dropdown on the package directory.

<img width="1253" alt="Screenshot 2022-07-02 at 11 08 43" src="https://user-images.githubusercontent.com/24275922/176994251-62406e8e-3432-405e-b997-017a6f42d796.png">

**Comment by nul800sebastiaan** [comment]
Thanks @dalyUSN - it's 9+ now in line with the other "dotnet core compatible" package indicators.

**Comment by dalyUSN** [comment]
Nice one, @nul800sebastiaan. That's definitely much better.

However, there will probably still be a number of cases where a package works on 9 but not on 10 and vice versa. 

Would it be better if the version dropdown was more specific so that users do not filter to v9+ and then try to install packages that will not work on v10?

**Comment by nul800sebastiaan** [comment]
I know, we'll work on that later, this was just a little update for now, but it's a lot harder to be more specific (for now).

**Comment by dalyUSN** [comment]
No problem, appreciate the update. Thanks!
