### ISSUE TITLE
Report compatibility options

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/OurUmbraco#782]
When reporting the compatibility of a package users are now presented with a very long list of versions.

Is it time to remove at least the v7 versions from this list? I appreciate that not every site is likely to be on 8,9 or 10, however, I would imagine that for the most part, v7 packages are no longer supported and no existing v7 site is likely to install a package at this point. 

Additionally, when reporting the compatibility of a package, the button to initiate the report is at the bottom of the really long list. It could very easily be missed. 

I suggest we remove v7 versions from the list and move the report compatibility button to the top of the list (or, at least, have a button at the top and bottom of the list).

![screencapture-our-umbraco-packages-starter-kits-uskinned-site-builder-2022-07-02-12_18_44](https://user-images.githubusercontent.com/24275922/176996489-e956a88a-af9c-438d-a2e4-7f90977b6e65.png)

**Comment by nul800sebastiaan** [comment]
Good suggestions! Moved the report button up and limited to 8.18 and v9/10 now. We'll need to re-evaluate this whole system in the future, but I think this will do for now, thanks!

**Comment by dalyUSN** [comment]
Nice one, thanks!
