### ISSUE TITLE
Can't upload packages...

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/OurUmbraco#816]
Trying to upload a patch for one of my older packages but the form just does a 302 and the file never gets uploaded...

**Comment by nul800sebastiaan** [comment]
The UI is not very intuitive, yes, a 302 but then you get back to the list, I just tried uploading one and it work, just need to mark it as active now.
![image](https://user-images.githubusercontent.com/304656/214003867-5342d2b3-8b6f-4430-be2b-ce81ccee1f7b.png)

**Comment by nul800sebastiaan** [comment]
If that didn't work for you then usually there's no (valid) package.xml in the root. If you've checked that then upload the zip and I can have a look.

**Comment by callumbwhyte** [comment]
Perhaps there's something wrong with my file then...

[Our.Umbraco.SuperValueConverters.v2.2.1.zip](https://github.com/umbraco/OurUmbraco/files/10478282/Our.Umbraco.SuperValueConverters.v2.2.1.zip)

**Comment by nul800sebastiaan** [comment]
Yep, the first line of `package.xml` is blank, so the XML parser doesn't like it, when fixing that it works!

**Comment by callumbwhyte** [comment]
Gah! Thanks...!
