### ISSUE TITLE
Error on loading project

### ISSUE THREAD

**Issue by bobhu1** [umbraco/OurUmbraco#845]
Downloaded the latest code  from Github and tried to run in VS 2022. The solution can not load OurUmbraco.Site project. Error: 
The imported project "$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" was not found. Also, tried to find "$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0"

**Comment by nul800sebastiaan** [comment]
We're currently not doing much active maintenance on this repository, what is it you were trying to contribute once you got the build to work?

**Comment by bobhu1** [comment]
Thanks a lot, I just want to build a website and want to learn from this
project.

**Comment by nul800sebastiaan** [comment]
Oh please don't learn from this, this is a 12 year old legacy project and everything in here is hacked together and horrible! Please head on over to https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website and learn much better ways! ❤️
